package apierror

// frozenCodes is the FROZEN compatibility table (F1-D, decision F1-D2):
// every error message the API ships today mapped to its machine code,
// snapshotted verbatim from the historical derivation. These values are a
// live contract with the web and mobile frontends — they may be ADDED to,
// but an existing value must NEVER change and an existing key must NEVER be
// removed while any client still branches on it.
//
// Editing an error sentence in a handler therefore CANNOT silently change
// its code: the message-literal contract test (registry_test.go) fails until
// the new sentence is deliberately registered here, and the old entry stays
// behind for old clients. Genuinely new messages fall back to derived codes
// (see Code) until registered.
//
//nolint:gochecknoglobals,gosec // frozen contract table, read-only at runtime; the "credentials"-looking keys are error-message sentences, not secrets
var frozenCodes = map[string]string{
	// Explicit auth codes (pre-F1-D, SCREAMING_SNAKE by design).
	"missing authorization header":        CodeAuthHeaderMissing,
	"invalid authorization header format": CodeAuthHeaderInvalid,
	"invalid or expired token":            CodeAuthTokenInvalid,
	"unauthorized":                        CodeAuthUnauthorized,
	"invalid credentials":                 CodeAuthCredentials,
	"email not verified":                  CodeAuthEmailUnverified,
	"too many auth attempts":              CodeAuthRateLimited,

	// Handler/middleware literals (snapshot of the derived snake_case codes).
	"active khatam cycle already exists": "active_khatam_cycle_already_exists",
	"book not found":                     "book_not_found",
	"cannot change own role":             "cannot_change_own_role",
	"cannot demote the last admin":       "cannot_demote_the_last_admin",
	"database problems":                  "database_problems",
	"draft not found":                    "draft_not_found",
	"email delivery failed":              "email_delivery_failed",
	"empty batch":                        "empty_batch",
	"feedback not found":                 "feedback_not_found",
	"forbidden":                          "forbidden",
	"heading not found":                  "heading_not_found",
	"if-match header required":           "if_match_header_required",
	"internal server error":              "internal_server_error",
	"invalid activity date":              "invalid_activity_date",
	"invalid activity range":             "invalid_activity_range",
	"invalid asset type":                 "invalid_asset_type",
	"invalid asset_type":                 "invalid_asset_type",
	"invalid author_id":                  "invalid_author_id",
	"invalid ayah key":                   "invalid_ayah_key",
	"invalid book_id":                    "invalid_book_id",
	"invalid category_id":                "invalid_category_id",
	"invalid collection slug":            "invalid_collection_slug",
	"invalid email_verified":             "invalid_email_verified",
	"invalid feedback":                   "invalid_feedback",
	"invalid feedback id":                "invalid_feedback_id",
	"invalid from":                       "invalid_from",
	"invalid has_content":                "invalid_has_content",
	"invalid heading_id":                 "invalid_heading_id",
	"invalid hizb_number":                "invalid_hizb_number",
	"invalid include_audio":              "invalid_include_audio",
	"invalid include_info":               "invalid_include_info",
	"invalid include_quran_references":   "invalid_include_quran_references",
	"invalid include_translation":        "invalid_include_translation",
	"invalid juz_number":                 "invalid_juz_number",
	"invalid needs_work":                 "invalid_needs_work",
	"invalid page_id":                    "invalid_page_id",
	"invalid production draft":           "invalid_production_draft",
	"invalid question":                   "invalid_question",
	"invalid quran progress":             "invalid_quran_progress",
	"invalid quran range":                "invalid_quran_range",
	"invalid reader location":            "invalid_reader_location",
	"invalid reading progress":           "invalid_reading_progress",
	"invalid ready_to_publish":           "invalid_ready_to_publish",
	"invalid refresh token":              "invalid_refresh_token",
	"invalid request":                    "invalid_request",
	"invalid request body":               "invalid_request_body",
	"invalid review decision":            "invalid_review_decision",
	"invalid role":                       "invalid_role",
	"invalid saved item":                 "invalid_saved_item",
	"invalid service token":              "invalid_service_token",
	"invalid since":                      "invalid_since",
	"invalid status":                     "invalid_status",
	"invalid status transition":          "invalid_status_transition",
	"invalid surah_id":                   "invalid_surah_id",
	"invalid task status":                "invalid_task_status",
	"invalid to":                         "invalid_to",
	"invalid unstarted":                  "invalid_unstarted",
	"invalid unsubscribe token":          "invalid_unsubscribe_token",
	"invalid user preference":            "invalid_user_preference",
	"invalid verification token":         "invalid_verification_token",
	"invalid view":                       "invalid_view",
	"khatam cycle incomplete":            "khatam_cycle_incomplete",
	"khatam cycle not found":             "khatam_cycle_not_found",
	"not found":                          "not_found",
	"page not found":                     "page_not_found",
	"password reset email recently sent": "password_reset_email_recently_sent",
	"precondition failed":                "precondition_failed",
	"production project already exists":  "production_project_already_exists",
	"production project is not ready":    "production_project_is_not_ready",
	"production project not found":       "production_project_not_found",
	"progress not found":                 "progress_not_found",
	"quran ayah not found":               "quran_ayah_not_found",
	"quran is not configured":            "quran_is_not_configured",
	"quran navigation not found":         "quran_navigation_not_found",
	"quran recitation not found":         "quran_recitation_not_found",
	"quran surah not found":              "quran_surah_not_found",
	"quran translation source not found": "quran_translation_source_not_found",
	"rag evidence not found":             "rag_evidence_not_found",
	"rag is not configured":              "rag_is_not_configured",
	"rag llm is not configured":          "rag_llm_is_not_configured",
	"saved item not found":               "saved_item_not_found",
	"session not found":                  "session_not_found",
	"task not found":                     "task_not_found",
	"translation not found":              "translation_not_found",
	"translation service problems":       "translation_service_problems",
	"unsupported language":               "unsupported_language",
	"user already exists":                "user_already_exists",
	"user not found":                     "user_not_found",
	"verification email recently sent":   "verification_email_recently_sent",

	// Entity error strings that reach clients via err.Error() passthroughs
	// (adminEmailError and friends) — frozen the same way.
	"email message not resendable": "email_message_not_resendable",
	"email recipient suppressed":   "email_recipient_suppressed",
	"invalid auth input":           "invalid_auth_input",
	"invalid email campaign":       "invalid_email_campaign",
	"invalid email template":       "invalid_email_template",

	// Envelope-wide messages introduced by F1-D itself (rate limiters,
	// framework error handler, catch-all 404).
	"too many requests":        "too_many_requests",
	"method not allowed":       "method_not_allowed",
	"request entity too large": "request_entity_too_large",
}
