package entity

import "errors"

var (
	ErrUserNotFound               = errors.New("user not found")
	ErrUserAlreadyExists          = errors.New("user already exists")
	ErrInvalidAuthInput           = errors.New("invalid auth input")
	ErrInvalidCredentials         = errors.New("invalid credentials")
	ErrEmailNotVerified           = errors.New("email not verified")
	ErrInvalidVerificationToken   = errors.New("invalid verification token")
	ErrVerificationTokenNotFound  = errors.New("verification token not found")
	ErrEmailDeliveryFailed        = errors.New("email delivery failed")
	ErrAuthRateLimited            = errors.New("auth rate limited")
	ErrTokenRevoked               = errors.New("token revoked")
	ErrVerificationRateLimited    = errors.New("verification email rate limited")
	ErrInvalidPasswordResetToken  = errors.New("invalid password reset token")
	ErrPasswordResetTokenNotFound = errors.New("password reset token not found")
	ErrPasswordResetRateLimited   = errors.New("password reset rate limited")
	ErrTaskNotFound               = errors.New("task not found")
	ErrTaskForbidden              = errors.New("task does not belong to user")
	ErrInvalidTransition          = errors.New("invalid status transition")
	ErrBookNotFound               = errors.New("book not found")
	ErrPageNotFound               = errors.New("page not found")
	ErrHeadingNotFound            = errors.New("heading not found")
	ErrTranslationNotFound        = errors.New("translation not found")
	ErrUnsupportedLanguage        = errors.New("unsupported language")
	ErrFeedbackNotFound           = errors.New("feedback not found")
	ErrBookmarkNotFound           = errors.New("bookmark not found")
	ErrProgressNotFound           = errors.New("reading progress not found")
	ErrInvalidReaderLocation      = errors.New("invalid reader location")
	ErrInvalidFeedback            = errors.New("invalid feedback")
	ErrInvalidQuestion            = errors.New("invalid question")
	ErrRAGNotConfigured           = errors.New("rag llm is not configured")
	ErrRAGEvidenceNotFound        = errors.New("rag evidence not found")
	ErrForbidden                  = errors.New("forbidden")
	ErrInvalidRole                = errors.New("invalid role")
	ErrInvalidStatus              = errors.New("invalid status")
	ErrDraftNotFound              = errors.New("draft not found")
	ErrQuranSurahNotFound         = errors.New("quran surah not found")
	ErrQuranAyahNotFound          = errors.New("quran ayah not found")
	ErrQuranRecitationNotFound    = errors.New("quran recitation not found")
	ErrInvalidAyahKey             = errors.New("invalid ayah key")
	ErrInvalidQuranRange          = errors.New("invalid quran range")
)
