// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: docs/proto/v1/auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	EmailVerified bool                   `protobuf:"varint,6,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RegisterResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RegisterResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Otp           string                 `protobuf:"bytes,3,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailRequest) Reset() {
	*x = VerifyEmailRequest{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailRequest) ProtoMessage() {}

func (x *VerifyEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailRequest.ProtoReflect.Descriptor instead.
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyEmailRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VerifyEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyEmailRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type VerifyEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailVerified bool                   `protobuf:"varint,1,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailResponse) Reset() {
	*x = VerifyEmailResponse{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailResponse) ProtoMessage() {}

func (x *VerifyEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailResponse.ProtoReflect.Descriptor instead.
func (*VerifyEmailResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyEmailResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

type ResendEmailVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendEmailVerificationRequest) Reset() {
	*x = ResendEmailVerificationRequest{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendEmailVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendEmailVerificationRequest) ProtoMessage() {}

func (x *ResendEmailVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendEmailVerificationRequest.ProtoReflect.Descriptor instead.
func (*ResendEmailVerificationRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ResendEmailVerificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ResendEmailVerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendEmailVerificationResponse) Reset() {
	*x = ResendEmailVerificationResponse{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendEmailVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendEmailVerificationResponse) ProtoMessage() {}

func (x *ResendEmailVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendEmailVerificationResponse.ProtoReflect.Descriptor instead.
func (*ResendEmailVerificationResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ResendEmailVerificationResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type ForgotPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordRequest) Reset() {
	*x = ForgotPasswordRequest{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordRequest) ProtoMessage() {}

func (x *ForgotPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordRequest.ProtoReflect.Descriptor instead.
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ForgotPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ForgotPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordResponse) Reset() {
	*x = ForgotPasswordResponse{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordResponse) ProtoMessage() {}

func (x *ForgotPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordResponse.ProtoReflect.Descriptor instead.
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ForgotPasswordResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ResetPasswordRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResetPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PasswordReset bool                   `protobuf:"varint,1,opt,name=password_reset,json=passwordReset,proto3" json:"password_reset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ResetPasswordResponse) GetPasswordReset() bool {
	if x != nil {
		return x.PasswordReset
	}
	return false
}

type ChangePasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentPassword string                 `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *ChangePasswordRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PasswordChanged bool                   `protobuf:"varint,1,opt,name=password_changed,json=passwordChanged,proto3" json:"password_changed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *ChangePasswordResponse) GetPasswordChanged() bool {
	if x != nil {
		return x.PasswordChanged
	}
	return false
}

type RequestEmailChangeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentPassword string                 `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewEmail        string                 `protobuf:"bytes,2,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestEmailChangeRequest) Reset() {
	*x = RequestEmailChangeRequest{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEmailChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEmailChangeRequest) ProtoMessage() {}

func (x *RequestEmailChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEmailChangeRequest.ProtoReflect.Descriptor instead.
func (*RequestEmailChangeRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *RequestEmailChangeRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *RequestEmailChangeRequest) GetNewEmail() string {
	if x != nil {
		return x.NewEmail
	}
	return ""
}

type RequestEmailChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEmailChangeResponse) Reset() {
	*x = RequestEmailChangeResponse{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEmailChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEmailChangeResponse) ProtoMessage() {}

func (x *RequestEmailChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEmailChangeResponse.ProtoReflect.Descriptor instead.
func (*RequestEmailChangeResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *RequestEmailChangeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type VerifyEmailChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailChangeRequest) Reset() {
	*x = VerifyEmailChangeRequest{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailChangeRequest) ProtoMessage() {}

func (x *VerifyEmailChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailChangeRequest.ProtoReflect.Descriptor instead.
func (*VerifyEmailChangeRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{16}
}

func (x *VerifyEmailChangeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VerifyEmailChangeRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type VerifyEmailChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailChanged  bool                   `protobuf:"varint,1,opt,name=email_changed,json=emailChanged,proto3" json:"email_changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailChangeResponse) Reset() {
	*x = VerifyEmailChangeResponse{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailChangeResponse) ProtoMessage() {}

func (x *VerifyEmailChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailChangeResponse.ProtoReflect.Descriptor instead.
func (*VerifyEmailChangeResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *VerifyEmailChangeResponse) GetEmailChanged() bool {
	if x != nil {
		return x.EmailChanged
	}
	return false
}

type DeleteAccountRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentPassword string                 `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteAccountRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

type DeleteAccountResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountDeleted bool                   `protobuf:"varint,1,opt,name=account_deleted,json=accountDeleted,proto3" json:"account_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteAccountResponse) GetAccountDeleted() bool {
	if x != nil {
		return x.AccountDeleted
	}
	return false
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{20}
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	EmailVerified bool                   `protobuf:"varint,6,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{21}
}

func (x *GetProfileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetProfileResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetProfileResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetProfileResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

var File_docs_proto_v1_auth_proto protoreflect.FileDescriptor

const file_docs_proto_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x18docs/proto/v1/auth.proto\x12\agrpc.v1\"\x96\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"\xb9\x01\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12%\n" +
	"\x0eemail_verified\x18\x06 \x01(\bR\remailVerified\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"R\n" +
	"\x12VerifyEmailRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x10\n" +
	"\x03otp\x18\x03 \x01(\tR\x03otp\"<\n" +
	"\x13VerifyEmailResponse\x12%\n" +
	"\x0eemail_verified\x18\x01 \x01(\bR\remailVerified\"6\n" +
	"\x1eResendEmailVerificationRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"=\n" +
	"\x1fResendEmailVerificationResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"-\n" +
	"\x15ForgotPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"4\n" +
	"\x16ForgotPasswordResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"H\n" +
	"\x14ResetPasswordRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\">\n" +
	"\x15ResetPasswordResponse\x12%\n" +
	"\x0epassword_reset\x18\x01 \x01(\bR\rpasswordReset\"e\n" +
	"\x15ChangePasswordRequest\x12)\n" +
	"\x10current_password\x18\x01 \x01(\tR\x0fcurrentPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"C\n" +
	"\x16ChangePasswordResponse\x12)\n" +
	"\x10password_changed\x18\x01 \x01(\bR\x0fpasswordChanged\"c\n" +
	"\x19RequestEmailChangeRequest\x12)\n" +
	"\x10current_password\x18\x01 \x01(\tR\x0fcurrentPassword\x12\x1b\n" +
	"\tnew_email\x18\x02 \x01(\tR\bnewEmail\"8\n" +
	"\x1aRequestEmailChangeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"B\n" +
	"\x18VerifyEmailChangeRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\tR\x03otp\"@\n" +
	"\x19VerifyEmailChangeResponse\x12#\n" +
	"\remail_changed\x18\x01 \x01(\bR\femailChanged\"A\n" +
	"\x14DeleteAccountRequest\x12)\n" +
	"\x10current_password\x18\x01 \x01(\tR\x0fcurrentPassword\"@\n" +
	"\x15DeleteAccountResponse\x12'\n" +
	"\x0faccount_deleted\x18\x01 \x01(\bR\x0eaccountDeleted\"\x13\n" +
	"\x11GetProfileRequest\"\xbb\x01\n" +
	"\x12GetProfileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12%\n" +
	"\x0eemail_verified\x18\x06 \x01(\bR\remailVerified2\x86\a\n" +
	"\vAuthService\x12?\n" +
	"\bRegister\x12\x18.grpc.v1.RegisterRequest\x1a\x19.grpc.v1.RegisterResponse\x126\n" +
	"\x05Login\x12\x15.grpc.v1.LoginRequest\x1a\x16.grpc.v1.LoginResponse\x12H\n" +
	"\vVerifyEmail\x12\x1b.grpc.v1.VerifyEmailRequest\x1a\x1c.grpc.v1.VerifyEmailResponse\x12l\n" +
	"\x17ResendEmailVerification\x12'.grpc.v1.ResendEmailVerificationRequest\x1a(.grpc.v1.ResendEmailVerificationResponse\x12Q\n" +
	"\x0eForgotPassword\x12\x1e.grpc.v1.ForgotPasswordRequest\x1a\x1f.grpc.v1.ForgotPasswordResponse\x12N\n" +
	"\rResetPassword\x12\x1d.grpc.v1.ResetPasswordRequest\x1a\x1e.grpc.v1.ResetPasswordResponse\x12Q\n" +
	"\x0eChangePassword\x12\x1e.grpc.v1.ChangePasswordRequest\x1a\x1f.grpc.v1.ChangePasswordResponse\x12]\n" +
	"\x12RequestEmailChange\x12\".grpc.v1.RequestEmailChangeRequest\x1a#.grpc.v1.RequestEmailChangeResponse\x12Z\n" +
	"\x11VerifyEmailChange\x12!.grpc.v1.VerifyEmailChangeRequest\x1a\".grpc.v1.VerifyEmailChangeResponse\x12N\n" +
	"\rDeleteAccount\x12\x1d.grpc.v1.DeleteAccountRequest\x1a\x1e.grpc.v1.DeleteAccountResponse\x12E\n" +
	"\n" +
	"GetProfile\x12\x1a.grpc.v1.GetProfileRequest\x1a\x1b.grpc.v1.GetProfileResponseB\x0fZ\rdocs/proto/v1b\x06proto3"

var (
	file_docs_proto_v1_auth_proto_rawDescOnce sync.Once
	file_docs_proto_v1_auth_proto_rawDescData []byte
)

func file_docs_proto_v1_auth_proto_rawDescGZIP() []byte {
	file_docs_proto_v1_auth_proto_rawDescOnce.Do(func() {
		file_docs_proto_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_proto_v1_auth_proto_rawDesc), len(file_docs_proto_v1_auth_proto_rawDesc)))
	})
	return file_docs_proto_v1_auth_proto_rawDescData
}

var file_docs_proto_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_docs_proto_v1_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),                 // 0: grpc.v1.RegisterRequest
	(*RegisterResponse)(nil),                // 1: grpc.v1.RegisterResponse
	(*LoginRequest)(nil),                    // 2: grpc.v1.LoginRequest
	(*LoginResponse)(nil),                   // 3: grpc.v1.LoginResponse
	(*VerifyEmailRequest)(nil),              // 4: grpc.v1.VerifyEmailRequest
	(*VerifyEmailResponse)(nil),             // 5: grpc.v1.VerifyEmailResponse
	(*ResendEmailVerificationRequest)(nil),  // 6: grpc.v1.ResendEmailVerificationRequest
	(*ResendEmailVerificationResponse)(nil), // 7: grpc.v1.ResendEmailVerificationResponse
	(*ForgotPasswordRequest)(nil),           // 8: grpc.v1.ForgotPasswordRequest
	(*ForgotPasswordResponse)(nil),          // 9: grpc.v1.ForgotPasswordResponse
	(*ResetPasswordRequest)(nil),            // 10: grpc.v1.ResetPasswordRequest
	(*ResetPasswordResponse)(nil),           // 11: grpc.v1.ResetPasswordResponse
	(*ChangePasswordRequest)(nil),           // 12: grpc.v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil),          // 13: grpc.v1.ChangePasswordResponse
	(*RequestEmailChangeRequest)(nil),       // 14: grpc.v1.RequestEmailChangeRequest
	(*RequestEmailChangeResponse)(nil),      // 15: grpc.v1.RequestEmailChangeResponse
	(*VerifyEmailChangeRequest)(nil),        // 16: grpc.v1.VerifyEmailChangeRequest
	(*VerifyEmailChangeResponse)(nil),       // 17: grpc.v1.VerifyEmailChangeResponse
	(*DeleteAccountRequest)(nil),            // 18: grpc.v1.DeleteAccountRequest
	(*DeleteAccountResponse)(nil),           // 19: grpc.v1.DeleteAccountResponse
	(*GetProfileRequest)(nil),               // 20: grpc.v1.GetProfileRequest
	(*GetProfileResponse)(nil),              // 21: grpc.v1.GetProfileResponse
}
var file_docs_proto_v1_auth_proto_depIdxs = []int32{
	0,  // 0: grpc.v1.AuthService.Register:input_type -> grpc.v1.RegisterRequest
	2,  // 1: grpc.v1.AuthService.Login:input_type -> grpc.v1.LoginRequest
	4,  // 2: grpc.v1.AuthService.VerifyEmail:input_type -> grpc.v1.VerifyEmailRequest
	6,  // 3: grpc.v1.AuthService.ResendEmailVerification:input_type -> grpc.v1.ResendEmailVerificationRequest
	8,  // 4: grpc.v1.AuthService.ForgotPassword:input_type -> grpc.v1.ForgotPasswordRequest
	10, // 5: grpc.v1.AuthService.ResetPassword:input_type -> grpc.v1.ResetPasswordRequest
	12, // 6: grpc.v1.AuthService.ChangePassword:input_type -> grpc.v1.ChangePasswordRequest
	14, // 7: grpc.v1.AuthService.RequestEmailChange:input_type -> grpc.v1.RequestEmailChangeRequest
	16, // 8: grpc.v1.AuthService.VerifyEmailChange:input_type -> grpc.v1.VerifyEmailChangeRequest
	18, // 9: grpc.v1.AuthService.DeleteAccount:input_type -> grpc.v1.DeleteAccountRequest
	20, // 10: grpc.v1.AuthService.GetProfile:input_type -> grpc.v1.GetProfileRequest
	1,  // 11: grpc.v1.AuthService.Register:output_type -> grpc.v1.RegisterResponse
	3,  // 12: grpc.v1.AuthService.Login:output_type -> grpc.v1.LoginResponse
	5,  // 13: grpc.v1.AuthService.VerifyEmail:output_type -> grpc.v1.VerifyEmailResponse
	7,  // 14: grpc.v1.AuthService.ResendEmailVerification:output_type -> grpc.v1.ResendEmailVerificationResponse
	9,  // 15: grpc.v1.AuthService.ForgotPassword:output_type -> grpc.v1.ForgotPasswordResponse
	11, // 16: grpc.v1.AuthService.ResetPassword:output_type -> grpc.v1.ResetPasswordResponse
	13, // 17: grpc.v1.AuthService.ChangePassword:output_type -> grpc.v1.ChangePasswordResponse
	15, // 18: grpc.v1.AuthService.RequestEmailChange:output_type -> grpc.v1.RequestEmailChangeResponse
	17, // 19: grpc.v1.AuthService.VerifyEmailChange:output_type -> grpc.v1.VerifyEmailChangeResponse
	19, // 20: grpc.v1.AuthService.DeleteAccount:output_type -> grpc.v1.DeleteAccountResponse
	21, // 21: grpc.v1.AuthService.GetProfile:output_type -> grpc.v1.GetProfileResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_docs_proto_v1_auth_proto_init() }
func file_docs_proto_v1_auth_proto_init() {
	if File_docs_proto_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_proto_v1_auth_proto_rawDesc), len(file_docs_proto_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_v1_auth_proto_goTypes,
		DependencyIndexes: file_docs_proto_v1_auth_proto_depIdxs,
		MessageInfos:      file_docs_proto_v1_auth_proto_msgTypes,
	}.Build()
	File_docs_proto_v1_auth_proto = out.File
	file_docs_proto_v1_auth_proto_goTypes = nil
	file_docs_proto_v1_auth_proto_depIdxs = nil
}
