//go:build normalization_generator

// Command gen_v1_unicode snapshots the Go Unicode 15.0 letter/digit
// classification used by search-key/v1. It deliberately refuses newer tables.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"unicode"
)

const (
	frozenUnicodeVersion = "15.0.0"
	generatedFileMode    = 0o600
)

type codePointRange struct {
	Lo int
	Hi int
}

func main() {
	if unicode.Version != frozenUnicodeVersion {
		panic(fmt.Sprintf("refusing to regenerate v1 with Unicode %s (want %s)", unicode.Version, frozenUnicodeVersion))
	}

	ranges := collectRanges()

	var artifact bytes.Buffer
	artifact.WriteString("{\n")
	artifact.WriteString("  \"profile\": {\"name\": \"search-key\", \"version\": 1},\n")
	artifact.WriteString("  \"source_unicode_version\": \"15.0.0\",\n")
	artifact.WriteString("  \"ranges\": [\n")

	for index, item := range ranges {
		comma := ","
		if index == len(ranges)-1 {
			comma = ""
		}

		fmt.Fprintf(&artifact, "    [%d, %d]%s\n", item.Lo, item.Hi, comma)
	}

	artifact.WriteString("  ]\n}\n")
	check(os.WriteFile("normalization_v1_unicode_ranges.json", artifact.Bytes(), generatedFileMode))

	var source bytes.Buffer
	source.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	source.WriteString("package quranutil\n\n")
	source.WriteString("var normalizationV1LetterDigitRanges = [...]unicodeV1Range{\n")

	for _, item := range ranges {
		fmt.Fprintf(&source, "\t{lo: 0x%X, hi: 0x%X},\n", item.Lo, item.Hi)
	}

	source.WriteString("}\n")

	formatted, err := format.Source(source.Bytes())
	check(err)
	check(os.WriteFile("normalization_v1_unicode_ranges_gen.go", formatted, generatedFileMode))
}

func collectRanges() []codePointRange {
	var ranges []codePointRange

	start := -1

	for codePoint := 0; codePoint <= unicode.MaxRune; codePoint++ {
		accepted := unicode.IsLetter(rune(codePoint)) || unicode.IsDigit(rune(codePoint))
		if accepted && start == -1 {
			start = codePoint
		}

		if !accepted && start != -1 {
			ranges = append(ranges, codePointRange{Lo: start, Hi: codePoint - 1})
			start = -1
		}
	}

	if start != -1 {
		ranges = append(ranges, codePointRange{Lo: start, Hi: unicode.MaxRune})
	}

	return ranges
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
