package diffcover

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParseUnifiedDiff(t *testing.T) {
	t.Parallel()

	t.Run("collects added lines per file across hunks", func(t *testing.T) {
		t.Parallel()

		diff := `diff --git a/internal/foo/foo.go b/internal/foo/foo.go
--- a/internal/foo/foo.go
+++ b/internal/foo/foo.go
@@ -10,2 +10,3 @@ func Foo() {
 context
+added ten plus one
+added ten plus two
@@ -30 +31,2 @@
+thirty one
+thirty two
diff --git a/pkg/bar/bar.go b/pkg/bar/bar.go
--- a/pkg/bar/bar.go
+++ b/pkg/bar/bar.go
@@ -0,0 +1,2 @@
+package bar
+var X = 1
`

		added, err := ParseUnifiedDiff(strings.NewReader(diff))
		require.NoError(t, err)

		assert.Equal(t, []int{11, 12, 31, 32}, added["internal/foo/foo.go"])
		assert.Equal(t, []int{1, 2}, added["pkg/bar/bar.go"])
	})

	t.Run("counts context lines but not removals", func(t *testing.T) {
		t.Parallel()

		diff := `--- a/x.go
+++ b/x.go
@@ -5,3 +5,3 @@
 ctx line five
-removed
+added six
 ctx line seven
`

		added, err := ParseUnifiedDiff(strings.NewReader(diff))
		require.NoError(t, err)
		assert.Equal(t, []int{6}, added["x.go"])
	})

	t.Run("skips deleted files (no post-image)", func(t *testing.T) {
		t.Parallel()

		diff := `--- a/gone.go
+++ /dev/null
@@ -1,3 +0,0 @@
-a
-b
-c
`

		added, err := ParseUnifiedDiff(strings.NewReader(diff))
		require.NoError(t, err)
		assert.Empty(t, added)
	})

	t.Run("rejects malformed hunk headers", func(t *testing.T) {
		t.Parallel()

		diff := `--- a/x.go
+++ b/x.go
@@ nonsense @@
+line
`

		_, err := ParseUnifiedDiff(strings.NewReader(diff))
		require.Error(t, err)
		assert.Contains(t, err.Error(), "malformed hunk header")
	})
}

func TestJoinLineRanges(t *testing.T) {
	t.Parallel()

	assert.Empty(t, joinLineRanges(nil))
	assert.Equal(t, "7", joinLineRanges([]int{7}))
	assert.Equal(t, "1-3", joinLineRanges([]int{1, 2, 3}))
	assert.Equal(t, "1-2, 5, 9-10", joinLineRanges([]int{1, 2, 5, 9, 10}))
}

func TestIsGeneratedSource(t *testing.T) {
	t.Parallel()

	assert.True(t, isGeneratedSource([]byte("// Code generated by mockery. DO NOT EDIT.\npackage x\n")))
	assert.False(t, isGeneratedSource([]byte("package x\n\nfunc F() {}\n")))
}

func TestStmtStartLines(t *testing.T) {
	t.Parallel()

	src := []byte(`package x

import "fmt"

type T struct {
	A int
}

func F(v int) int {
	if v > 0 {
		fmt.Println(v)
	}

	return v + 1
}
`)

	lines, err := stmtStartLines("x.go", src)
	require.NoError(t, err)

	assert.True(t, lines[10], "if statement line")
	assert.True(t, lines[11], "call statement line")
	assert.True(t, lines[14], "return statement line")
	assert.False(t, lines[3], "import is not a statement")
	assert.False(t, lines[5], "type decl is not a statement")

	_, err = stmtStartLines("broken.go", []byte("package x\nfunc {"))
	require.Error(t, err)
}

// writeRepo lays out a throwaway repo root with the given files.
func writeRepo(t *testing.T, files map[string]string) string {
	t.Helper()

	root := t.TempDir()

	for path, content := range files {
		full := filepath.Join(root, filepath.FromSlash(path))
		require.NoError(t, os.MkdirAll(filepath.Dir(full), 0o755))
		require.NoError(t, os.WriteFile(full, []byte(content), 0o600))
	}

	return root
}

func writeFile(t *testing.T, dir, name, content string) string {
	t.Helper()

	path := filepath.Join(dir, name)
	require.NoError(t, os.WriteFile(path, []byte(content), 0o600))

	return path
}

const testModule = "example.com/mod"

const coveredSource = `package foo

func Covered(v int) int {
	v++
	return v
}
`

func TestAnalyze(t *testing.T) {
	t.Parallel()

	t.Run("union of profiles: live coverage rescues unit-uncovered lines", func(t *testing.T) {
		t.Parallel()

		root := writeRepo(t, map[string]string{"internal/foo/foo.go": coveredSource})

		unit := writeFile(t, t.TempDir(), "unit.txt", `mode: atomic
example.com/mod/internal/foo/foo.go:3.22,6.2 2 0
`)
		live := writeFile(t, t.TempDir(), "live.txt", `mode: atomic
example.com/mod/internal/foo/foo.go:3.22,6.2 2 7
`)

		diff := `--- a/internal/foo/foo.go
+++ b/internal/foo/foo.go
@@ -3,0 +4,2 @@
+	v++
+	return v
`

		unitOnly, err := Analyze(strings.NewReader(diff), []string{unit}, Options{
			ModulePath: testModule, ScopeDirs: []string{"internal/", "pkg/"}, RepoRoot: root,
		})
		require.NoError(t, err)
		assert.Equal(t, 2, unitOnly.ChangedStmts)
		assert.Zero(t, unitOnly.CoveredStmts)
		assert.False(t, unitOnly.Pass(70))

		both, err := Analyze(strings.NewReader(diff), []string{unit, live}, Options{
			ModulePath: testModule, ScopeDirs: []string{"internal/", "pkg/"}, RepoRoot: root,
		})
		require.NoError(t, err)
		assert.Equal(t, 2, both.ChangedStmts)
		assert.Equal(t, 2, both.CoveredStmts)
		assert.True(t, both.Pass(70))
		assert.InDelta(t, 100.0, both.DiffPercent(), 0.01)

		// The union counts the shared block once in the repo-wide totals.
		assert.Equal(t, 2, both.TotalStmts)
		assert.Equal(t, 2, both.TotalCovered)
		assert.InDelta(t, 100.0, both.TotalPercent(), 0.01)
	})

	t.Run("file absent from every profile counts as fully uncovered", func(t *testing.T) {
		t.Parallel()

		root := writeRepo(t, map[string]string{"internal/nu/nu.go": coveredSource})

		profile := writeFile(t, t.TempDir(), "unit.txt", `mode: atomic
example.com/mod/internal/other/other.go:1.1,2.2 1 1
`)

		diff := `--- /dev/null
+++ b/internal/nu/nu.go
@@ -0,0 +1,6 @@
+package foo
+
+func Covered(v int) int {
+	v++
+	return v
+}
`

		result, err := Analyze(strings.NewReader(diff), []string{profile}, Options{
			ModulePath: testModule, ScopeDirs: []string{"internal/"}, RepoRoot: root,
		})
		require.NoError(t, err)
		require.Len(t, result.Files, 1)
		assert.False(t, result.Files[0].InProfiles)
		assert.Equal(t, 2, result.ChangedStmts, "the two body statements")
		assert.Zero(t, result.CoveredStmts)
		assert.Equal(t, []int{4, 5}, result.Files[0].UncoveredLines)
		assert.False(t, result.Pass(70))
	})

	t.Run("scope rules: tests, generated, and foreign paths do not count", func(t *testing.T) {
		t.Parallel()

		root := writeRepo(t, map[string]string{
			"internal/gen/gen.go": "// Code generated by tooling. DO NOT EDIT.\npackage gen\n\nfunc G() { _ = 1 }\n",
			"cmd/tool/main.go":    coveredSource,
		})

		profile := writeFile(t, t.TempDir(), "unit.txt", "mode: atomic\n")

		diff := `--- a/internal/gen/gen.go
+++ b/internal/gen/gen.go
@@ -3,0 +4,1 @@
+func G() { _ = 1 }
--- a/cmd/tool/main.go
+++ b/cmd/tool/main.go
@@ -3,0 +4,1 @@
+	v++
--- a/internal/foo/foo_test.go
+++ b/internal/foo/foo_test.go
@@ -3,0 +4,1 @@
+	v++
--- a/docs/readme.md
+++ b/docs/readme.md
@@ -1,0 +2,1 @@
+prose
`

		result, err := Analyze(strings.NewReader(diff), []string{profile}, Options{
			ModulePath: testModule, ScopeDirs: []string{"internal/", "pkg/"}, RepoRoot: root,
		})
		require.NoError(t, err)
		assert.Empty(t, result.Files)
		assert.Zero(t, result.ChangedStmts)
		assert.True(t, result.Pass(70), "nothing measurable changed → pass")
		assert.InDelta(t, 100.0, result.DiffPercent(), 0.01)
	})

	t.Run("changed non-statement lines in profiled files are free", func(t *testing.T) {
		t.Parallel()

		root := writeRepo(t, map[string]string{"internal/foo/foo.go": coveredSource})

		profile := writeFile(t, t.TempDir(), "unit.txt", `mode: atomic
example.com/mod/internal/foo/foo.go:3.22,6.2 2 1
`)

		// Line 1 (package clause) is outside every block.
		diff := `--- a/internal/foo/foo.go
+++ b/internal/foo/foo.go
@@ -1,1 +1,1 @@
+package foo
`

		result, err := Analyze(strings.NewReader(diff), []string{profile}, Options{
			ModulePath: testModule, ScopeDirs: []string{"internal/"}, RepoRoot: root,
		})
		require.NoError(t, err)
		assert.Zero(t, result.ChangedStmts)
		assert.Empty(t, result.Files)
	})

	t.Run("partially covered diff computes a percentage and uncovered ranges", func(t *testing.T) {
		t.Parallel()

		source := `package foo

func A() int {
	return 1
}

func B() int {
	return 2
}
`
		root := writeRepo(t, map[string]string{"internal/foo/foo.go": source})

		profile := writeFile(t, t.TempDir(), "unit.txt", `mode: atomic
example.com/mod/internal/foo/foo.go:3.14,5.2 1 5
example.com/mod/internal/foo/foo.go:7.14,9.2 1 0
`)

		diff := `--- a/internal/foo/foo.go
+++ b/internal/foo/foo.go
@@ -4,0 +4,1 @@
+	return 1
@@ -8,0 +8,1 @@
+	return 2
`

		result, err := Analyze(strings.NewReader(diff), []string{profile}, Options{
			ModulePath: testModule, ScopeDirs: []string{"internal/"}, RepoRoot: root,
		})
		require.NoError(t, err)
		assert.Equal(t, 2, result.ChangedStmts)
		assert.Equal(t, 1, result.CoveredStmts)
		assert.InDelta(t, 50.0, result.DiffPercent(), 0.01)
		assert.False(t, result.Pass(70))
		require.Len(t, result.Files, 1)
		assert.Equal(t, []int{8}, result.Files[0].UncoveredLines)

		text := RenderText(result, 70)
		assert.Contains(t, text, "diff coverage: 50.0%")
		assert.Contains(t, text, "uncovered lines: 8")

		markdown := RenderMarkdown(result, 70)
		assert.Contains(t, markdown, "❌ FAIL")
		assert.Contains(t, markdown, "<!-- diffcover -->")
		assert.Contains(t, markdown, "`internal/foo/foo.go`")
	})

	t.Run("empty diff passes and renders the no-change note", func(t *testing.T) {
		t.Parallel()

		profile := writeFile(t, t.TempDir(), "unit.txt", "mode: atomic\n")

		result, err := Analyze(strings.NewReader(""), []string{profile}, Options{
			ModulePath: testModule, ScopeDirs: []string{"internal/"}, RepoRoot: t.TempDir(),
		})
		require.NoError(t, err)
		assert.True(t, result.Pass(70))

		markdown := RenderMarkdown(result, 70)
		assert.Contains(t, markdown, "✅ PASS")
		assert.Contains(t, markdown, "gate passes by definition")
	})

	t.Run("missing module path and unreadable inputs error", func(t *testing.T) {
		t.Parallel()

		_, err := Analyze(strings.NewReader(""), nil, Options{})
		require.Error(t, err)

		_, err = Analyze(strings.NewReader(""), []string{filepath.Join(t.TempDir(), "nope.txt")}, Options{
			ModulePath: testModule, ScopeDirs: []string{"internal/"}, RepoRoot: t.TempDir(),
		})
		require.Error(t, err)

		diff := `--- a/internal/foo/foo.go
+++ b/internal/foo/foo.go
@@ -1,0 +1,1 @@
+package foo
`
		profile := writeFile(t, t.TempDir(), "unit.txt", "mode: atomic\n")

		_, err = Analyze(strings.NewReader(diff), []string{profile}, Options{
			ModulePath: testModule, ScopeDirs: []string{"internal/"}, RepoRoot: t.TempDir(),
		})
		require.Error(t, err, "changed file missing from the working tree")
	})
}
