// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/repo/contracts.go -destination ./internal/usecase/mocks_repo_test.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/evrone/go-clean-template/internal/entity"
	repo "github.com/evrone/go-clean-template/internal/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslationRepo is a mock of TranslationRepo interface.
type MockTranslationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationRepoMockRecorder
	isgomock struct{}
}

// MockTranslationRepoMockRecorder is the mock recorder for MockTranslationRepo.
type MockTranslationRepoMockRecorder struct {
	mock *MockTranslationRepo
}

// NewMockTranslationRepo creates a new mock instance.
func NewMockTranslationRepo(ctrl *gomock.Controller) *MockTranslationRepo {
	mock := &MockTranslationRepo{ctrl: ctrl}
	mock.recorder = &MockTranslationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationRepo) EXPECT() *MockTranslationRepoMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockTranslationRepo) GetHistory(ctx context.Context, userID string) ([]entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, userID)
	ret0, _ := ret[0].([]entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockTranslationRepoMockRecorder) GetHistory(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockTranslationRepo)(nil).GetHistory), ctx, userID)
}

// Store mocks base method.
func (m *MockTranslationRepo) Store(ctx context.Context, userID string, t entity.Translation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, userID, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTranslationRepoMockRecorder) Store(ctx, userID, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTranslationRepo)(nil).Store), ctx, userID, t)
}

// MockTranslationWebAPI is a mock of TranslationWebAPI interface.
type MockTranslationWebAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationWebAPIMockRecorder
	isgomock struct{}
}

// MockTranslationWebAPIMockRecorder is the mock recorder for MockTranslationWebAPI.
type MockTranslationWebAPIMockRecorder struct {
	mock *MockTranslationWebAPI
}

// NewMockTranslationWebAPI creates a new mock instance.
func NewMockTranslationWebAPI(ctrl *gomock.Controller) *MockTranslationWebAPI {
	mock := &MockTranslationWebAPI{ctrl: ctrl}
	mock.recorder = &MockTranslationWebAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationWebAPI) EXPECT() *MockTranslationWebAPIMockRecorder {
	return m.recorder
}

// Translate mocks base method.
func (m *MockTranslationWebAPI) Translate(ctx context.Context, t entity.Translation) (entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", ctx, t)
	ret0, _ := ret[0].(entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationWebAPIMockRecorder) Translate(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslationWebAPI)(nil).Translate), ctx, t)
}

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// GetByEmail mocks base method.
func (m *MockUserRepo) GetByEmail(ctx context.Context, email string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepoMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepo) GetByID(ctx context.Context, id string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepo)(nil).GetByID), ctx, id)
}

// SetRoleByEmail mocks base method.
func (m *MockUserRepo) SetRoleByEmail(ctx context.Context, email, role string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRoleByEmail", ctx, email, role)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetRoleByEmail indicates an expected call of SetRoleByEmail.
func (mr *MockUserRepoMockRecorder) SetRoleByEmail(ctx, email, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoleByEmail", reflect.TypeOf((*MockUserRepo)(nil).SetRoleByEmail), ctx, email, role)
}

// Store mocks base method.
func (m *MockUserRepo) Store(ctx context.Context, user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockUserRepoMockRecorder) Store(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockUserRepo)(nil).Store), ctx, user)
}

// MockTaskRepo is a mock of TaskRepo interface.
type MockTaskRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepoMockRecorder
	isgomock struct{}
}

// MockTaskRepoMockRecorder is the mock recorder for MockTaskRepo.
type MockTaskRepoMockRecorder struct {
	mock *MockTaskRepo
}

// NewMockTaskRepo creates a new mock instance.
func NewMockTaskRepo(ctrl *gomock.Controller) *MockTaskRepo {
	mock := &MockTaskRepo{ctrl: ctrl}
	mock.recorder = &MockTaskRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepo) EXPECT() *MockTaskRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTaskRepo) Delete(ctx context.Context, userID, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskRepoMockRecorder) Delete(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaskRepo)(nil).Delete), ctx, userID, taskID)
}

// GetByID mocks base method.
func (m *MockTaskRepo) GetByID(ctx context.Context, userID, taskID string) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID, taskID)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTaskRepoMockRecorder) GetByID(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTaskRepo)(nil).GetByID), ctx, userID, taskID)
}

// List mocks base method.
func (m *MockTaskRepo) List(ctx context.Context, userID string, filter repo.TaskFilter) ([]entity.Task, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, filter)
	ret0, _ := ret[0].([]entity.Task)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTaskRepoMockRecorder) List(ctx, userID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskRepo)(nil).List), ctx, userID, filter)
}

// Store mocks base method.
func (m *MockTaskRepo) Store(ctx context.Context, task *entity.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTaskRepoMockRecorder) Store(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTaskRepo)(nil).Store), ctx, task)
}

// Update mocks base method.
func (m *MockTaskRepo) Update(ctx context.Context, task *entity.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTaskRepoMockRecorder) Update(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskRepo)(nil).Update), ctx, task)
}

// MockReaderRepo is a mock of ReaderRepo interface.
type MockReaderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockReaderRepoMockRecorder
	isgomock struct{}
}

// MockReaderRepoMockRecorder is the mock recorder for MockReaderRepo.
type MockReaderRepoMockRecorder struct {
	mock *MockReaderRepo
}

// NewMockReaderRepo creates a new mock instance.
func NewMockReaderRepo(ctrl *gomock.Controller) *MockReaderRepo {
	mock := &MockReaderRepo{ctrl: ctrl}
	mock.recorder = &MockReaderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReaderRepo) EXPECT() *MockReaderRepoMockRecorder {
	return m.recorder
}

// CreateTranslationFeedback mocks base method.
func (m *MockReaderRepo) CreateTranslationFeedback(ctx context.Context, feedback entity.TranslationFeedback) (entity.TranslationFeedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTranslationFeedback", ctx, feedback)
	ret0, _ := ret[0].(entity.TranslationFeedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTranslationFeedback indicates an expected call of CreateTranslationFeedback.
func (mr *MockReaderRepoMockRecorder) CreateTranslationFeedback(ctx, feedback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTranslationFeedback", reflect.TypeOf((*MockReaderRepo)(nil).CreateTranslationFeedback), ctx, feedback)
}

// GetBook mocks base method.
func (m *MockReaderRepo) GetBook(ctx context.Context, bookID int, lang string) (entity.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBook", ctx, bookID, lang)
	ret0, _ := ret[0].(entity.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBook indicates an expected call of GetBook.
func (mr *MockReaderRepoMockRecorder) GetBook(ctx, bookID, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBook", reflect.TypeOf((*MockReaderRepo)(nil).GetBook), ctx, bookID, lang)
}

// GetBookPage mocks base method.
func (m *MockReaderRepo) GetBookPage(ctx context.Context, bookID, pageID int) (entity.BookPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookPage", ctx, bookID, pageID)
	ret0, _ := ret[0].(entity.BookPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookPage indicates an expected call of GetBookPage.
func (mr *MockReaderRepoMockRecorder) GetBookPage(ctx, bookID, pageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookPage", reflect.TypeOf((*MockReaderRepo)(nil).GetBookPage), ctx, bookID, pageID)
}

// GetSection mocks base method.
func (m *MockReaderRepo) GetSection(ctx context.Context, bookID, headingID int, lang string) (entity.BookSection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSection", ctx, bookID, headingID, lang)
	ret0, _ := ret[0].(entity.BookSection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSection indicates an expected call of GetSection.
func (mr *MockReaderRepoMockRecorder) GetSection(ctx, bookID, headingID, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSection", reflect.TypeOf((*MockReaderRepo)(nil).GetSection), ctx, bookID, headingID, lang)
}

// ListAuthors mocks base method.
func (m *MockReaderRepo) ListAuthors(ctx context.Context, filter repo.AuthorFilter) ([]entity.Author, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuthors", ctx, filter)
	ret0, _ := ret[0].([]entity.Author)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAuthors indicates an expected call of ListAuthors.
func (mr *MockReaderRepoMockRecorder) ListAuthors(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuthors", reflect.TypeOf((*MockReaderRepo)(nil).ListAuthors), ctx, filter)
}

// ListBookHeadings mocks base method.
func (m *MockReaderRepo) ListBookHeadings(ctx context.Context, bookID int, query string) ([]entity.BookHeading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookHeadings", ctx, bookID, query)
	ret0, _ := ret[0].([]entity.BookHeading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBookHeadings indicates an expected call of ListBookHeadings.
func (mr *MockReaderRepoMockRecorder) ListBookHeadings(ctx, bookID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookHeadings", reflect.TypeOf((*MockReaderRepo)(nil).ListBookHeadings), ctx, bookID, query)
}

// ListBookPages mocks base method.
func (m *MockReaderRepo) ListBookPages(ctx context.Context, bookID int, filter repo.PageFilter) ([]entity.BookPage, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookPages", ctx, bookID, filter)
	ret0, _ := ret[0].([]entity.BookPage)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBookPages indicates an expected call of ListBookPages.
func (mr *MockReaderRepoMockRecorder) ListBookPages(ctx, bookID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookPages", reflect.TypeOf((*MockReaderRepo)(nil).ListBookPages), ctx, bookID, filter)
}

// ListBooks mocks base method.
func (m *MockReaderRepo) ListBooks(ctx context.Context, filter repo.BookFilter) ([]entity.Book, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBooks", ctx, filter)
	ret0, _ := ret[0].([]entity.Book)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBooks indicates an expected call of ListBooks.
func (mr *MockReaderRepoMockRecorder) ListBooks(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBooks", reflect.TypeOf((*MockReaderRepo)(nil).ListBooks), ctx, filter)
}

// ListCategories mocks base method.
func (m *MockReaderRepo) ListCategories(ctx context.Context, lang string) ([]entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", ctx, lang)
	ret0, _ := ret[0].([]entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockReaderRepoMockRecorder) ListCategories(ctx, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockReaderRepo)(nil).ListCategories), ctx, lang)
}

// ListTOCEntries mocks base method.
func (m *MockReaderRepo) ListTOCEntries(ctx context.Context, bookID int, lang string, includeAudio bool) ([]entity.BookTOCEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTOCEntries", ctx, bookID, lang, includeAudio)
	ret0, _ := ret[0].([]entity.BookTOCEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTOCEntries indicates an expected call of ListTOCEntries.
func (mr *MockReaderRepoMockRecorder) ListTOCEntries(ctx, bookID, lang, includeAudio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTOCEntries", reflect.TypeOf((*MockReaderRepo)(nil).ListTOCEntries), ctx, bookID, lang, includeAudio)
}

// MockBookRAGRepo is a mock of BookRAGRepo interface.
type MockBookRAGRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBookRAGRepoMockRecorder
	isgomock struct{}
}

// MockBookRAGRepoMockRecorder is the mock recorder for MockBookRAGRepo.
type MockBookRAGRepoMockRecorder struct {
	mock *MockBookRAGRepo
}

// NewMockBookRAGRepo creates a new mock instance.
func NewMockBookRAGRepo(ctrl *gomock.Controller) *MockBookRAGRepo {
	mock := &MockBookRAGRepo{ctrl: ctrl}
	mock.recorder = &MockBookRAGRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookRAGRepo) EXPECT() *MockBookRAGRepoMockRecorder {
	return m.recorder
}

// GetRAGBookDocument mocks base method.
func (m *MockBookRAGRepo) GetRAGBookDocument(ctx context.Context, bookID int, lang string) (entity.RAGBookDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRAGBookDocument", ctx, bookID, lang)
	ret0, _ := ret[0].(entity.RAGBookDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRAGBookDocument indicates an expected call of GetRAGBookDocument.
func (mr *MockBookRAGRepoMockRecorder) GetRAGBookDocument(ctx, bookID, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRAGBookDocument", reflect.TypeOf((*MockBookRAGRepo)(nil).GetRAGBookDocument), ctx, bookID, lang)
}

// GetRAGPageSources mocks base method.
func (m *MockBookRAGRepo) GetRAGPageSources(ctx context.Context, bookID int, headingIDs, focusPageIDs []int, lang string, maxPages int) ([]entity.RAGPageSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRAGPageSources", ctx, bookID, headingIDs, focusPageIDs, lang, maxPages)
	ret0, _ := ret[0].([]entity.RAGPageSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRAGPageSources indicates an expected call of GetRAGPageSources.
func (mr *MockBookRAGRepoMockRecorder) GetRAGPageSources(ctx, bookID, headingIDs, focusPageIDs, lang, maxPages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRAGPageSources", reflect.TypeOf((*MockBookRAGRepo)(nil).GetRAGPageSources), ctx, bookID, headingIDs, focusPageIDs, lang, maxPages)
}

// ListRAGStructure mocks base method.
func (m *MockBookRAGRepo) ListRAGStructure(ctx context.Context, bookID int, lang string) ([]entity.RAGStructureNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRAGStructure", ctx, bookID, lang)
	ret0, _ := ret[0].([]entity.RAGStructureNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRAGStructure indicates an expected call of ListRAGStructure.
func (mr *MockBookRAGRepoMockRecorder) ListRAGStructure(ctx, bookID, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRAGStructure", reflect.TypeOf((*MockBookRAGRepo)(nil).ListRAGStructure), ctx, bookID, lang)
}

// SearchRAGPages mocks base method.
func (m *MockBookRAGRepo) SearchRAGPages(ctx context.Context, bookID int, query, lang string, limit int) ([]entity.RAGSearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRAGPages", ctx, bookID, query, lang, limit)
	ret0, _ := ret[0].([]entity.RAGSearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRAGPages indicates an expected call of SearchRAGPages.
func (mr *MockBookRAGRepoMockRecorder) SearchRAGPages(ctx, bookID, query, lang, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRAGPages", reflect.TypeOf((*MockBookRAGRepo)(nil).SearchRAGPages), ctx, bookID, query, lang, limit)
}

// MockPersonalRepo is a mock of PersonalRepo interface.
type MockPersonalRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPersonalRepoMockRecorder
	isgomock struct{}
}

// MockPersonalRepoMockRecorder is the mock recorder for MockPersonalRepo.
type MockPersonalRepoMockRecorder struct {
	mock *MockPersonalRepo
}

// NewMockPersonalRepo creates a new mock instance.
func NewMockPersonalRepo(ctrl *gomock.Controller) *MockPersonalRepo {
	mock := &MockPersonalRepo{ctrl: ctrl}
	mock.recorder = &MockPersonalRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonalRepo) EXPECT() *MockPersonalRepoMockRecorder {
	return m.recorder
}

// CreateBookmark mocks base method.
func (m *MockPersonalRepo) CreateBookmark(ctx context.Context, bookmark entity.Bookmark) (entity.Bookmark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBookmark", ctx, bookmark)
	ret0, _ := ret[0].(entity.Bookmark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBookmark indicates an expected call of CreateBookmark.
func (mr *MockPersonalRepoMockRecorder) CreateBookmark(ctx, bookmark any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBookmark", reflect.TypeOf((*MockPersonalRepo)(nil).CreateBookmark), ctx, bookmark)
}

// DeleteBookmark mocks base method.
func (m *MockPersonalRepo) DeleteBookmark(ctx context.Context, userID, bookmarkID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookmark", ctx, userID, bookmarkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBookmark indicates an expected call of DeleteBookmark.
func (mr *MockPersonalRepoMockRecorder) DeleteBookmark(ctx, userID, bookmarkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookmark", reflect.TypeOf((*MockPersonalRepo)(nil).DeleteBookmark), ctx, userID, bookmarkID)
}

// GetProgress mocks base method.
func (m *MockPersonalRepo) GetProgress(ctx context.Context, userID string, bookID int) (entity.ReadingProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProgress", ctx, userID, bookID)
	ret0, _ := ret[0].(entity.ReadingProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProgress indicates an expected call of GetProgress.
func (mr *MockPersonalRepoMockRecorder) GetProgress(ctx, userID, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProgress", reflect.TypeOf((*MockPersonalRepo)(nil).GetProgress), ctx, userID, bookID)
}

// ListBookmarks mocks base method.
func (m *MockPersonalRepo) ListBookmarks(ctx context.Context, userID string, filter repo.BookmarkFilter) ([]entity.Bookmark, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookmarks", ctx, userID, filter)
	ret0, _ := ret[0].([]entity.Bookmark)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBookmarks indicates an expected call of ListBookmarks.
func (mr *MockPersonalRepoMockRecorder) ListBookmarks(ctx, userID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookmarks", reflect.TypeOf((*MockPersonalRepo)(nil).ListBookmarks), ctx, userID, filter)
}

// SaveProgress mocks base method.
func (m *MockPersonalRepo) SaveProgress(ctx context.Context, progress entity.ReadingProgress) (entity.ReadingProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveProgress", ctx, progress)
	ret0, _ := ret[0].(entity.ReadingProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveProgress indicates an expected call of SaveProgress.
func (mr *MockPersonalRepoMockRecorder) SaveProgress(ctx, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveProgress", reflect.TypeOf((*MockPersonalRepo)(nil).SaveProgress), ctx, progress)
}

// MockEditorialRepo is a mock of EditorialRepo interface.
type MockEditorialRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEditorialRepoMockRecorder
	isgomock struct{}
}

// MockEditorialRepoMockRecorder is the mock recorder for MockEditorialRepo.
type MockEditorialRepoMockRecorder struct {
	mock *MockEditorialRepo
}

// NewMockEditorialRepo creates a new mock instance.
func NewMockEditorialRepo(ctrl *gomock.Controller) *MockEditorialRepo {
	mock := &MockEditorialRepo{ctrl: ctrl}
	mock.recorder = &MockEditorialRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEditorialRepo) EXPECT() *MockEditorialRepoMockRecorder {
	return m.recorder
}

// AddCollectionItem mocks base method.
func (m *MockEditorialRepo) AddCollectionItem(ctx context.Context, actorID, slug string, bookID int, sortOrder *int) (entity.BookCollectionItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCollectionItem", ctx, actorID, slug, bookID, sortOrder)
	ret0, _ := ret[0].(entity.BookCollectionItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCollectionItem indicates an expected call of AddCollectionItem.
func (mr *MockEditorialRepoMockRecorder) AddCollectionItem(ctx, actorID, slug, bookID, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCollectionItem", reflect.TypeOf((*MockEditorialRepo)(nil).AddCollectionItem), ctx, actorID, slug, bookID, sortOrder)
}

// GetPageEdit mocks base method.
func (m *MockEditorialRepo) GetPageEdit(ctx context.Context, bookID, pageID int) (entity.AdminPageEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPageEdit", ctx, bookID, pageID)
	ret0, _ := ret[0].(entity.AdminPageEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPageEdit indicates an expected call of GetPageEdit.
func (mr *MockEditorialRepoMockRecorder) GetPageEdit(ctx, bookID, pageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPageEdit", reflect.TypeOf((*MockEditorialRepo)(nil).GetPageEdit), ctx, bookID, pageID)
}

// ListBooks mocks base method.
func (m *MockEditorialRepo) ListBooks(ctx context.Context, filter repo.EditorialBookFilter) ([]entity.Book, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBooks", ctx, filter)
	ret0, _ := ret[0].([]entity.Book)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBooks indicates an expected call of ListBooks.
func (mr *MockEditorialRepoMockRecorder) ListBooks(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBooks", reflect.TypeOf((*MockEditorialRepo)(nil).ListBooks), ctx, filter)
}

// ListTranslationFeedbacks mocks base method.
func (m *MockEditorialRepo) ListTranslationFeedbacks(ctx context.Context, filter repo.TranslationFeedbackFilter) ([]entity.AdminTranslationFeedback, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTranslationFeedbacks", ctx, filter)
	ret0, _ := ret[0].([]entity.AdminTranslationFeedback)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTranslationFeedbacks indicates an expected call of ListTranslationFeedbacks.
func (mr *MockEditorialRepoMockRecorder) ListTranslationFeedbacks(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTranslationFeedbacks", reflect.TypeOf((*MockEditorialRepo)(nil).ListTranslationFeedbacks), ctx, filter)
}

// PublishHeadingDraft mocks base method.
func (m *MockEditorialRepo) PublishHeadingDraft(ctx context.Context, actorID string, bookID, headingID int) (entity.BookHeadingEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishHeadingDraft", ctx, actorID, bookID, headingID)
	ret0, _ := ret[0].(entity.BookHeadingEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishHeadingDraft indicates an expected call of PublishHeadingDraft.
func (mr *MockEditorialRepoMockRecorder) PublishHeadingDraft(ctx, actorID, bookID, headingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishHeadingDraft", reflect.TypeOf((*MockEditorialRepo)(nil).PublishHeadingDraft), ctx, actorID, bookID, headingID)
}

// PublishMetadataDraft mocks base method.
func (m *MockEditorialRepo) PublishMetadataDraft(ctx context.Context, actorID string, bookID int) (entity.BookMetadataEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishMetadataDraft", ctx, actorID, bookID)
	ret0, _ := ret[0].(entity.BookMetadataEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishMetadataDraft indicates an expected call of PublishMetadataDraft.
func (mr *MockEditorialRepoMockRecorder) PublishMetadataDraft(ctx, actorID, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMetadataDraft", reflect.TypeOf((*MockEditorialRepo)(nil).PublishMetadataDraft), ctx, actorID, bookID)
}

// PublishPageDraft mocks base method.
func (m *MockEditorialRepo) PublishPageDraft(ctx context.Context, actorID string, bookID, pageID int) (entity.BookPageEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPageDraft", ctx, actorID, bookID, pageID)
	ret0, _ := ret[0].(entity.BookPageEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishPageDraft indicates an expected call of PublishPageDraft.
func (mr *MockEditorialRepoMockRecorder) PublishPageDraft(ctx, actorID, bookID, pageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPageDraft", reflect.TypeOf((*MockEditorialRepo)(nil).PublishPageDraft), ctx, actorID, bookID, pageID)
}

// ReopenTranslationFeedback mocks base method.
func (m *MockEditorialRepo) ReopenTranslationFeedback(ctx context.Context, actorID, feedbackID string) (entity.AdminTranslationFeedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReopenTranslationFeedback", ctx, actorID, feedbackID)
	ret0, _ := ret[0].(entity.AdminTranslationFeedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReopenTranslationFeedback indicates an expected call of ReopenTranslationFeedback.
func (mr *MockEditorialRepoMockRecorder) ReopenTranslationFeedback(ctx, actorID, feedbackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReopenTranslationFeedback", reflect.TypeOf((*MockEditorialRepo)(nil).ReopenTranslationFeedback), ctx, actorID, feedbackID)
}

// ResolveTranslationFeedback mocks base method.
func (m *MockEditorialRepo) ResolveTranslationFeedback(ctx context.Context, actorID, feedbackID string, note *string) (entity.AdminTranslationFeedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveTranslationFeedback", ctx, actorID, feedbackID, note)
	ret0, _ := ret[0].(entity.AdminTranslationFeedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveTranslationFeedback indicates an expected call of ResolveTranslationFeedback.
func (mr *MockEditorialRepoMockRecorder) ResolveTranslationFeedback(ctx, actorID, feedbackID, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveTranslationFeedback", reflect.TypeOf((*MockEditorialRepo)(nil).ResolveTranslationFeedback), ctx, actorID, feedbackID, note)
}

// SaveHeadingDraft mocks base method.
func (m *MockEditorialRepo) SaveHeadingDraft(ctx context.Context, actorID string, edit entity.BookHeadingEdit) (entity.BookHeadingEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveHeadingDraft", ctx, actorID, edit)
	ret0, _ := ret[0].(entity.BookHeadingEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveHeadingDraft indicates an expected call of SaveHeadingDraft.
func (mr *MockEditorialRepoMockRecorder) SaveHeadingDraft(ctx, actorID, edit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveHeadingDraft", reflect.TypeOf((*MockEditorialRepo)(nil).SaveHeadingDraft), ctx, actorID, edit)
}

// SaveMetadataDraft mocks base method.
func (m *MockEditorialRepo) SaveMetadataDraft(ctx context.Context, actorID string, edit entity.BookMetadataEdit) (entity.BookMetadataEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMetadataDraft", ctx, actorID, edit)
	ret0, _ := ret[0].(entity.BookMetadataEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMetadataDraft indicates an expected call of SaveMetadataDraft.
func (mr *MockEditorialRepoMockRecorder) SaveMetadataDraft(ctx, actorID, edit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMetadataDraft", reflect.TypeOf((*MockEditorialRepo)(nil).SaveMetadataDraft), ctx, actorID, edit)
}

// SavePageDraft mocks base method.
func (m *MockEditorialRepo) SavePageDraft(ctx context.Context, actorID string, edit entity.BookPageEdit) (entity.BookPageEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePageDraft", ctx, actorID, edit)
	ret0, _ := ret[0].(entity.BookPageEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SavePageDraft indicates an expected call of SavePageDraft.
func (mr *MockEditorialRepoMockRecorder) SavePageDraft(ctx, actorID, edit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePageDraft", reflect.TypeOf((*MockEditorialRepo)(nil).SavePageDraft), ctx, actorID, edit)
}

// TranslationFeedbackSummary mocks base method.
func (m *MockEditorialRepo) TranslationFeedbackSummary(ctx context.Context, filter repo.TranslationFeedbackFilter) (entity.AdminTranslationFeedbackSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranslationFeedbackSummary", ctx, filter)
	ret0, _ := ret[0].(entity.AdminTranslationFeedbackSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TranslationFeedbackSummary indicates an expected call of TranslationFeedbackSummary.
func (mr *MockEditorialRepoMockRecorder) TranslationFeedbackSummary(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranslationFeedbackSummary", reflect.TypeOf((*MockEditorialRepo)(nil).TranslationFeedbackSummary), ctx, filter)
}

// UpdatePublication mocks base method.
func (m *MockEditorialRepo) UpdatePublication(ctx context.Context, actorID string, publication entity.BookPublication) (entity.BookPublication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePublication", ctx, actorID, publication)
	ret0, _ := ret[0].(entity.BookPublication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePublication indicates an expected call of UpdatePublication.
func (mr *MockEditorialRepoMockRecorder) UpdatePublication(ctx, actorID, publication any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePublication", reflect.TypeOf((*MockEditorialRepo)(nil).UpdatePublication), ctx, actorID, publication)
}
