// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/contracts.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/contracts.go -destination=internal/usecase/mocks_usecase_test.go -package=usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/evrone/go-clean-template/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslation is a mock of Translation interface.
type MockTranslation struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationMockRecorder
	isgomock struct{}
}

// MockTranslationMockRecorder is the mock recorder for MockTranslation.
type MockTranslationMockRecorder struct {
	mock *MockTranslation
}

// NewMockTranslation creates a new mock instance.
func NewMockTranslation(ctrl *gomock.Controller) *MockTranslation {
	mock := &MockTranslation{ctrl: ctrl}
	mock.recorder = &MockTranslationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslation) EXPECT() *MockTranslationMockRecorder {
	return m.recorder
}

// History mocks base method.
func (m *MockTranslation) History(ctx context.Context, userID string) (entity.TranslationHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "History", ctx, userID)
	ret0, _ := ret[0].(entity.TranslationHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History.
func (mr *MockTranslationMockRecorder) History(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockTranslation)(nil).History), ctx, userID)
}

// Translate mocks base method.
func (m *MockTranslation) Translate(ctx context.Context, userID string, t entity.Translation) (entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", ctx, userID, t)
	ret0, _ := ret[0].(entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationMockRecorder) Translate(ctx, userID, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslation)(nil).Translate), ctx, userID, t)
}

// MockUser is a mock of User interface.
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
	isgomock struct{}
}

// MockUserMockRecorder is the mock recorder for MockUser.
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance.
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// GetUser mocks base method.
func (m *MockUser) GetUser(ctx context.Context, userID string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserMockRecorder) GetUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUser)(nil).GetUser), ctx, userID)
}

// Login mocks base method.
func (m *MockUser) Login(ctx context.Context, email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUser)(nil).Login), ctx, email, password)
}

// Register mocks base method.
func (m *MockUser) Register(ctx context.Context, username, email, password string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, username, email, password)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserMockRecorder) Register(ctx, username, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUser)(nil).Register), ctx, username, email, password)
}

// SetRoleByEmail mocks base method.
func (m *MockUser) SetRoleByEmail(ctx context.Context, email, role string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRoleByEmail", ctx, email, role)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetRoleByEmail indicates an expected call of SetRoleByEmail.
func (mr *MockUserMockRecorder) SetRoleByEmail(ctx, email, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoleByEmail", reflect.TypeOf((*MockUser)(nil).SetRoleByEmail), ctx, email, role)
}

// MockTask is a mock of Task interface.
type MockTask struct {
	ctrl     *gomock.Controller
	recorder *MockTaskMockRecorder
	isgomock struct{}
}

// MockTaskMockRecorder is the mock recorder for MockTask.
type MockTaskMockRecorder struct {
	mock *MockTask
}

// NewMockTask creates a new mock instance.
func NewMockTask(ctrl *gomock.Controller) *MockTask {
	mock := &MockTask{ctrl: ctrl}
	mock.recorder = &MockTaskMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTask) EXPECT() *MockTaskMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTask) Create(ctx context.Context, userID, title, description string) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, title, description)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTaskMockRecorder) Create(ctx, userID, title, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTask)(nil).Create), ctx, userID, title, description)
}

// Delete mocks base method.
func (m *MockTask) Delete(ctx context.Context, userID, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskMockRecorder) Delete(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTask)(nil).Delete), ctx, userID, taskID)
}

// Get mocks base method.
func (m *MockTask) Get(ctx context.Context, userID, taskID string) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, taskID)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTaskMockRecorder) Get(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTask)(nil).Get), ctx, userID, taskID)
}

// List mocks base method.
func (m *MockTask) List(ctx context.Context, userID string, status *entity.TaskStatus, limit, offset int) ([]entity.Task, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, status, limit, offset)
	ret0, _ := ret[0].([]entity.Task)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTaskMockRecorder) List(ctx, userID, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTask)(nil).List), ctx, userID, status, limit, offset)
}

// Transition mocks base method.
func (m *MockTask) Transition(ctx context.Context, userID, taskID string, newStatus entity.TaskStatus) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transition", ctx, userID, taskID, newStatus)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transition indicates an expected call of Transition.
func (mr *MockTaskMockRecorder) Transition(ctx, userID, taskID, newStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transition", reflect.TypeOf((*MockTask)(nil).Transition), ctx, userID, taskID, newStatus)
}

// Update mocks base method.
func (m *MockTask) Update(ctx context.Context, userID, taskID, title, description string) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userID, taskID, title, description)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTaskMockRecorder) Update(ctx, userID, taskID, title, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTask)(nil).Update), ctx, userID, taskID, title, description)
}

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// Authors mocks base method.
func (m *MockReader) Authors(ctx context.Context, query string, limit, offset int, lang string) ([]entity.Author, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authors", ctx, query, limit, offset, lang)
	ret0, _ := ret[0].([]entity.Author)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Authors indicates an expected call of Authors.
func (mr *MockReaderMockRecorder) Authors(ctx, query, limit, offset, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authors", reflect.TypeOf((*MockReader)(nil).Authors), ctx, query, limit, offset, lang)
}

// Book mocks base method.
func (m *MockReader) Book(ctx context.Context, bookID int, lang string) (entity.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Book", ctx, bookID, lang)
	ret0, _ := ret[0].(entity.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Book indicates an expected call of Book.
func (mr *MockReaderMockRecorder) Book(ctx, bookID, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Book", reflect.TypeOf((*MockReader)(nil).Book), ctx, bookID, lang)
}

// Books mocks base method.
func (m *MockReader) Books(ctx context.Context, query string, categoryID, authorID *int, hasContent *bool, limit, offset int, lang string) ([]entity.Book, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Books", ctx, query, categoryID, authorID, hasContent, limit, offset, lang)
	ret0, _ := ret[0].([]entity.Book)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Books indicates an expected call of Books.
func (mr *MockReaderMockRecorder) Books(ctx, query, categoryID, authorID, hasContent, limit, offset, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Books", reflect.TypeOf((*MockReader)(nil).Books), ctx, query, categoryID, authorID, hasContent, limit, offset, lang)
}

// Categories mocks base method.
func (m *MockReader) Categories(ctx context.Context, lang string) ([]entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Categories", ctx, lang)
	ret0, _ := ret[0].([]entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Categories indicates an expected call of Categories.
func (mr *MockReaderMockRecorder) Categories(ctx, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Categories", reflect.TypeOf((*MockReader)(nil).Categories), ctx, lang)
}

// Headings mocks base method.
func (m *MockReader) Headings(ctx context.Context, bookID int, query string) ([]entity.BookHeading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Headings", ctx, bookID, query)
	ret0, _ := ret[0].([]entity.BookHeading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Headings indicates an expected call of Headings.
func (mr *MockReaderMockRecorder) Headings(ctx, bookID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Headings", reflect.TypeOf((*MockReader)(nil).Headings), ctx, bookID, query)
}

// Page mocks base method.
func (m *MockReader) Page(ctx context.Context, bookID, pageID int) (entity.BookPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Page", ctx, bookID, pageID)
	ret0, _ := ret[0].(entity.BookPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Page indicates an expected call of Page.
func (mr *MockReaderMockRecorder) Page(ctx, bookID, pageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Page", reflect.TypeOf((*MockReader)(nil).Page), ctx, bookID, pageID)
}

// Pages mocks base method.
func (m *MockReader) Pages(ctx context.Context, bookID, limit, offset int) ([]entity.BookPage, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pages", ctx, bookID, limit, offset)
	ret0, _ := ret[0].([]entity.BookPage)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Pages indicates an expected call of Pages.
func (mr *MockReaderMockRecorder) Pages(ctx, bookID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pages", reflect.TypeOf((*MockReader)(nil).Pages), ctx, bookID, limit, offset)
}

// Section mocks base method.
func (m *MockReader) Section(ctx context.Context, bookID, headingID int, lang string) (entity.BookSection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Section", ctx, bookID, headingID, lang)
	ret0, _ := ret[0].(entity.BookSection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Section indicates an expected call of Section.
func (mr *MockReaderMockRecorder) Section(ctx, bookID, headingID, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Section", reflect.TypeOf((*MockReader)(nil).Section), ctx, bookID, headingID, lang)
}

// TOC mocks base method.
func (m *MockReader) TOC(ctx context.Context, bookID int, lang string, includeAudio bool) ([]entity.BookTOCNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TOC", ctx, bookID, lang, includeAudio)
	ret0, _ := ret[0].([]entity.BookTOCNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TOC indicates an expected call of TOC.
func (mr *MockReaderMockRecorder) TOC(ctx, bookID, lang, includeAudio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TOC", reflect.TypeOf((*MockReader)(nil).TOC), ctx, bookID, lang, includeAudio)
}

// TOCPlaylist mocks base method.
func (m *MockReader) TOCPlaylist(ctx context.Context, bookID, headingID int, lang string) (entity.BookTOCPlaylist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TOCPlaylist", ctx, bookID, headingID, lang)
	ret0, _ := ret[0].(entity.BookTOCPlaylist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TOCPlaylist indicates an expected call of TOCPlaylist.
func (mr *MockReaderMockRecorder) TOCPlaylist(ctx, bookID, headingID, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TOCPlaylist", reflect.TypeOf((*MockReader)(nil).TOCPlaylist), ctx, bookID, headingID, lang)
}

// TOCRead mocks base method.
func (m *MockReader) TOCRead(ctx context.Context, bookID, headingID int, lang string) (entity.BookTOCRead, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TOCRead", ctx, bookID, headingID, lang)
	ret0, _ := ret[0].(entity.BookTOCRead)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TOCRead indicates an expected call of TOCRead.
func (mr *MockReaderMockRecorder) TOCRead(ctx, bookID, headingID, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TOCRead", reflect.TypeOf((*MockReader)(nil).TOCRead), ctx, bookID, headingID, lang)
}

// MockPersonal is a mock of Personal interface.
type MockPersonal struct {
	ctrl     *gomock.Controller
	recorder *MockPersonalMockRecorder
	isgomock struct{}
}

// MockPersonalMockRecorder is the mock recorder for MockPersonal.
type MockPersonalMockRecorder struct {
	mock *MockPersonal
}

// NewMockPersonal creates a new mock instance.
func NewMockPersonal(ctrl *gomock.Controller) *MockPersonal {
	mock := &MockPersonal{ctrl: ctrl}
	mock.recorder = &MockPersonalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonal) EXPECT() *MockPersonalMockRecorder {
	return m.recorder
}

// CreateBookmark mocks base method.
func (m *MockPersonal) CreateBookmark(ctx context.Context, userID string, bookID int, pageID, headingID *int, label, note *string) (entity.Bookmark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBookmark", ctx, userID, bookID, pageID, headingID, label, note)
	ret0, _ := ret[0].(entity.Bookmark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBookmark indicates an expected call of CreateBookmark.
func (mr *MockPersonalMockRecorder) CreateBookmark(ctx, userID, bookID, pageID, headingID, label, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBookmark", reflect.TypeOf((*MockPersonal)(nil).CreateBookmark), ctx, userID, bookID, pageID, headingID, label, note)
}

// DeleteBookmark mocks base method.
func (m *MockPersonal) DeleteBookmark(ctx context.Context, userID, bookmarkID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookmark", ctx, userID, bookmarkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBookmark indicates an expected call of DeleteBookmark.
func (mr *MockPersonalMockRecorder) DeleteBookmark(ctx, userID, bookmarkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookmark", reflect.TypeOf((*MockPersonal)(nil).DeleteBookmark), ctx, userID, bookmarkID)
}

// GetProgress mocks base method.
func (m *MockPersonal) GetProgress(ctx context.Context, userID string, bookID int) (entity.ReadingProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProgress", ctx, userID, bookID)
	ret0, _ := ret[0].(entity.ReadingProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProgress indicates an expected call of GetProgress.
func (mr *MockPersonalMockRecorder) GetProgress(ctx, userID, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProgress", reflect.TypeOf((*MockPersonal)(nil).GetProgress), ctx, userID, bookID)
}

// ListBookmarks mocks base method.
func (m *MockPersonal) ListBookmarks(ctx context.Context, userID string, bookID *int, limit, offset int) ([]entity.Bookmark, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookmarks", ctx, userID, bookID, limit, offset)
	ret0, _ := ret[0].([]entity.Bookmark)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBookmarks indicates an expected call of ListBookmarks.
func (mr *MockPersonalMockRecorder) ListBookmarks(ctx, userID, bookID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookmarks", reflect.TypeOf((*MockPersonal)(nil).ListBookmarks), ctx, userID, bookID, limit, offset)
}

// SaveProgress mocks base method.
func (m *MockPersonal) SaveProgress(ctx context.Context, userID string, bookID int, pageID, headingID *int, progressPercent *float64) (entity.ReadingProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveProgress", ctx, userID, bookID, pageID, headingID, progressPercent)
	ret0, _ := ret[0].(entity.ReadingProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveProgress indicates an expected call of SaveProgress.
func (mr *MockPersonalMockRecorder) SaveProgress(ctx, userID, bookID, pageID, headingID, progressPercent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveProgress", reflect.TypeOf((*MockPersonal)(nil).SaveProgress), ctx, userID, bookID, pageID, headingID, progressPercent)
}

// MockEditorial is a mock of Editorial interface.
type MockEditorial struct {
	ctrl     *gomock.Controller
	recorder *MockEditorialMockRecorder
	isgomock struct{}
}

// MockEditorialMockRecorder is the mock recorder for MockEditorial.
type MockEditorialMockRecorder struct {
	mock *MockEditorial
}

// NewMockEditorial creates a new mock instance.
func NewMockEditorial(ctrl *gomock.Controller) *MockEditorial {
	mock := &MockEditorial{ctrl: ctrl}
	mock.recorder = &MockEditorialMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEditorial) EXPECT() *MockEditorialMockRecorder {
	return m.recorder
}

// AddCollectionItem mocks base method.
func (m *MockEditorial) AddCollectionItem(ctx context.Context, actorID, slug string, bookID int, sortOrder *int) (entity.BookCollectionItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCollectionItem", ctx, actorID, slug, bookID, sortOrder)
	ret0, _ := ret[0].(entity.BookCollectionItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCollectionItem indicates an expected call of AddCollectionItem.
func (mr *MockEditorialMockRecorder) AddCollectionItem(ctx, actorID, slug, bookID, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCollectionItem", reflect.TypeOf((*MockEditorial)(nil).AddCollectionItem), ctx, actorID, slug, bookID, sortOrder)
}

// Books mocks base method.
func (m *MockEditorial) Books(ctx context.Context, query string, status *string, categoryID *int, hasContent *bool, limit, offset int) ([]entity.Book, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Books", ctx, query, status, categoryID, hasContent, limit, offset)
	ret0, _ := ret[0].([]entity.Book)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Books indicates an expected call of Books.
func (mr *MockEditorialMockRecorder) Books(ctx, query, status, categoryID, hasContent, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Books", reflect.TypeOf((*MockEditorial)(nil).Books), ctx, query, status, categoryID, hasContent, limit, offset)
}

// GetPageEdit mocks base method.
func (m *MockEditorial) GetPageEdit(ctx context.Context, bookID, pageID int) (entity.AdminPageEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPageEdit", ctx, bookID, pageID)
	ret0, _ := ret[0].(entity.AdminPageEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPageEdit indicates an expected call of GetPageEdit.
func (mr *MockEditorialMockRecorder) GetPageEdit(ctx, bookID, pageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPageEdit", reflect.TypeOf((*MockEditorial)(nil).GetPageEdit), ctx, bookID, pageID)
}

// PublishHeadingDraft mocks base method.
func (m *MockEditorial) PublishHeadingDraft(ctx context.Context, actorID string, bookID, headingID int) (entity.BookHeadingEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishHeadingDraft", ctx, actorID, bookID, headingID)
	ret0, _ := ret[0].(entity.BookHeadingEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishHeadingDraft indicates an expected call of PublishHeadingDraft.
func (mr *MockEditorialMockRecorder) PublishHeadingDraft(ctx, actorID, bookID, headingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishHeadingDraft", reflect.TypeOf((*MockEditorial)(nil).PublishHeadingDraft), ctx, actorID, bookID, headingID)
}

// PublishMetadataDraft mocks base method.
func (m *MockEditorial) PublishMetadataDraft(ctx context.Context, actorID string, bookID int) (entity.BookMetadataEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishMetadataDraft", ctx, actorID, bookID)
	ret0, _ := ret[0].(entity.BookMetadataEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishMetadataDraft indicates an expected call of PublishMetadataDraft.
func (mr *MockEditorialMockRecorder) PublishMetadataDraft(ctx, actorID, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMetadataDraft", reflect.TypeOf((*MockEditorial)(nil).PublishMetadataDraft), ctx, actorID, bookID)
}

// PublishPageDraft mocks base method.
func (m *MockEditorial) PublishPageDraft(ctx context.Context, actorID string, bookID, pageID int) (entity.BookPageEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPageDraft", ctx, actorID, bookID, pageID)
	ret0, _ := ret[0].(entity.BookPageEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishPageDraft indicates an expected call of PublishPageDraft.
func (mr *MockEditorialMockRecorder) PublishPageDraft(ctx, actorID, bookID, pageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPageDraft", reflect.TypeOf((*MockEditorial)(nil).PublishPageDraft), ctx, actorID, bookID, pageID)
}

// SaveHeadingDraft mocks base method.
func (m *MockEditorial) SaveHeadingDraft(ctx context.Context, actorID string, edit entity.BookHeadingEdit) (entity.BookHeadingEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveHeadingDraft", ctx, actorID, edit)
	ret0, _ := ret[0].(entity.BookHeadingEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveHeadingDraft indicates an expected call of SaveHeadingDraft.
func (mr *MockEditorialMockRecorder) SaveHeadingDraft(ctx, actorID, edit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveHeadingDraft", reflect.TypeOf((*MockEditorial)(nil).SaveHeadingDraft), ctx, actorID, edit)
}

// SaveMetadataDraft mocks base method.
func (m *MockEditorial) SaveMetadataDraft(ctx context.Context, actorID string, edit entity.BookMetadataEdit) (entity.BookMetadataEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMetadataDraft", ctx, actorID, edit)
	ret0, _ := ret[0].(entity.BookMetadataEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMetadataDraft indicates an expected call of SaveMetadataDraft.
func (mr *MockEditorialMockRecorder) SaveMetadataDraft(ctx, actorID, edit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMetadataDraft", reflect.TypeOf((*MockEditorial)(nil).SaveMetadataDraft), ctx, actorID, edit)
}

// SavePageDraft mocks base method.
func (m *MockEditorial) SavePageDraft(ctx context.Context, actorID string, edit entity.BookPageEdit) (entity.BookPageEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePageDraft", ctx, actorID, edit)
	ret0, _ := ret[0].(entity.BookPageEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SavePageDraft indicates an expected call of SavePageDraft.
func (mr *MockEditorialMockRecorder) SavePageDraft(ctx, actorID, edit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePageDraft", reflect.TypeOf((*MockEditorial)(nil).SavePageDraft), ctx, actorID, edit)
}

// UpdatePublication mocks base method.
func (m *MockEditorial) UpdatePublication(ctx context.Context, actorID string, bookID int, status string, featured bool, sortOrder *int) (entity.BookPublication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePublication", ctx, actorID, bookID, status, featured, sortOrder)
	ret0, _ := ret[0].(entity.BookPublication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePublication indicates an expected call of UpdatePublication.
func (mr *MockEditorialMockRecorder) UpdatePublication(ctx, actorID, bookID, status, featured, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePublication", reflect.TypeOf((*MockEditorial)(nil).UpdatePublication), ctx, actorID, bookID, status, featured, sortOrder)
}
