// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/repo/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/evrone/go-clean-template/internal/entity"
	repo "github.com/evrone/go-clean-template/internal/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslationRepo is a mock of TranslationRepo interface.
type MockTranslationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationRepoMockRecorder
	isgomock struct{}
}

// MockTranslationRepoMockRecorder is the mock recorder for MockTranslationRepo.
type MockTranslationRepoMockRecorder struct {
	mock *MockTranslationRepo
}

// NewMockTranslationRepo creates a new mock instance.
func NewMockTranslationRepo(ctrl *gomock.Controller) *MockTranslationRepo {
	mock := &MockTranslationRepo{ctrl: ctrl}
	mock.recorder = &MockTranslationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationRepo) EXPECT() *MockTranslationRepoMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockTranslationRepo) GetHistory(ctx context.Context, userID string) ([]entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, userID)
	ret0, _ := ret[0].([]entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockTranslationRepoMockRecorder) GetHistory(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockTranslationRepo)(nil).GetHistory), ctx, userID)
}

// Store mocks base method.
func (m *MockTranslationRepo) Store(ctx context.Context, userID string, t entity.Translation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, userID, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTranslationRepoMockRecorder) Store(ctx, userID, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTranslationRepo)(nil).Store), ctx, userID, t)
}

// MockTranslationWebAPI is a mock of TranslationWebAPI interface.
type MockTranslationWebAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationWebAPIMockRecorder
	isgomock struct{}
}

// MockTranslationWebAPIMockRecorder is the mock recorder for MockTranslationWebAPI.
type MockTranslationWebAPIMockRecorder struct {
	mock *MockTranslationWebAPI
}

// NewMockTranslationWebAPI creates a new mock instance.
func NewMockTranslationWebAPI(ctrl *gomock.Controller) *MockTranslationWebAPI {
	mock := &MockTranslationWebAPI{ctrl: ctrl}
	mock.recorder = &MockTranslationWebAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationWebAPI) EXPECT() *MockTranslationWebAPIMockRecorder {
	return m.recorder
}

// Translate mocks base method.
func (m *MockTranslationWebAPI) Translate(ctx context.Context, t entity.Translation) (entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", ctx, t)
	ret0, _ := ret[0].(entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationWebAPIMockRecorder) Translate(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslationWebAPI)(nil).Translate), ctx, t)
}

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// AcquireAuthNotificationCooldown mocks base method.
func (m *MockUserRepo) AcquireAuthNotificationCooldown(ctx context.Context, cooldown entity.AuthNotificationCooldown) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireAuthNotificationCooldown", ctx, cooldown)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireAuthNotificationCooldown indicates an expected call of AcquireAuthNotificationCooldown.
func (mr *MockUserRepoMockRecorder) AcquireAuthNotificationCooldown(ctx, cooldown any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireAuthNotificationCooldown", reflect.TypeOf((*MockUserRepo)(nil).AcquireAuthNotificationCooldown), ctx, cooldown)
}

// ChangeEmailWithToken mocks base method.
func (m *MockUserRepo) ChangeEmailWithToken(ctx context.Context, tokenID, userID, newEmail string) (entity.EmailChangeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeEmailWithToken", ctx, tokenID, userID, newEmail)
	ret0, _ := ret[0].(entity.EmailChangeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeEmailWithToken indicates an expected call of ChangeEmailWithToken.
func (mr *MockUserRepoMockRecorder) ChangeEmailWithToken(ctx, tokenID, userID, newEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeEmailWithToken", reflect.TypeOf((*MockUserRepo)(nil).ChangeEmailWithToken), ctx, tokenID, userID, newEmail)
}

// ChangePassword mocks base method.
func (m *MockUserRepo) ChangePassword(ctx context.Context, userID, passwordHash string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, userID, passwordHash)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockUserRepoMockRecorder) ChangePassword(ctx, userID, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockUserRepo)(nil).ChangePassword), ctx, userID, passwordHash)
}

// DeleteAccount mocks base method.
func (m *MockUserRepo) DeleteAccount(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockUserRepoMockRecorder) DeleteAccount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockUserRepo)(nil).DeleteAccount), ctx, userID)
}

// GetAccount mocks base method.
func (m *MockUserRepo) GetAccount(ctx context.Context, userID string) (entity.UserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, userID)
	ret0, _ := ret[0].(entity.UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockUserRepoMockRecorder) GetAccount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockUserRepo)(nil).GetAccount), ctx, userID)
}

// GetByEmail mocks base method.
func (m *MockUserRepo) GetByEmail(ctx context.Context, email string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepoMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepo) GetByID(ctx context.Context, id string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepo)(nil).GetByID), ctx, id)
}

// GetEmailChangeTokenByHash mocks base method.
func (m *MockUserRepo) GetEmailChangeTokenByHash(ctx context.Context, tokenHash string) (entity.EmailChangeToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailChangeTokenByHash", ctx, tokenHash)
	ret0, _ := ret[0].(entity.EmailChangeToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailChangeTokenByHash indicates an expected call of GetEmailChangeTokenByHash.
func (mr *MockUserRepoMockRecorder) GetEmailChangeTokenByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailChangeTokenByHash", reflect.TypeOf((*MockUserRepo)(nil).GetEmailChangeTokenByHash), ctx, tokenHash)
}

// GetLatestUnusedEmailChangeToken mocks base method.
func (m *MockUserRepo) GetLatestUnusedEmailChangeToken(ctx context.Context, userID string) (entity.EmailChangeToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestUnusedEmailChangeToken", ctx, userID)
	ret0, _ := ret[0].(entity.EmailChangeToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestUnusedEmailChangeToken indicates an expected call of GetLatestUnusedEmailChangeToken.
func (mr *MockUserRepoMockRecorder) GetLatestUnusedEmailChangeToken(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestUnusedEmailChangeToken", reflect.TypeOf((*MockUserRepo)(nil).GetLatestUnusedEmailChangeToken), ctx, userID)
}

// GetLatestUnusedPasswordResetToken mocks base method.
func (m *MockUserRepo) GetLatestUnusedPasswordResetToken(ctx context.Context, userID string) (entity.PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestUnusedPasswordResetToken", ctx, userID)
	ret0, _ := ret[0].(entity.PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestUnusedPasswordResetToken indicates an expected call of GetLatestUnusedPasswordResetToken.
func (mr *MockUserRepoMockRecorder) GetLatestUnusedPasswordResetToken(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestUnusedPasswordResetToken", reflect.TypeOf((*MockUserRepo)(nil).GetLatestUnusedPasswordResetToken), ctx, userID)
}

// GetLatestUnusedVerificationToken mocks base method.
func (m *MockUserRepo) GetLatestUnusedVerificationToken(ctx context.Context, userID string) (entity.EmailVerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestUnusedVerificationToken", ctx, userID)
	ret0, _ := ret[0].(entity.EmailVerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestUnusedVerificationToken indicates an expected call of GetLatestUnusedVerificationToken.
func (mr *MockUserRepoMockRecorder) GetLatestUnusedVerificationToken(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestUnusedVerificationToken", reflect.TypeOf((*MockUserRepo)(nil).GetLatestUnusedVerificationToken), ctx, userID)
}

// GetPasswordResetTokenByHash mocks base method.
func (m *MockUserRepo) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (entity.PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasswordResetTokenByHash", ctx, tokenHash)
	ret0, _ := ret[0].(entity.PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasswordResetTokenByHash indicates an expected call of GetPasswordResetTokenByHash.
func (mr *MockUserRepoMockRecorder) GetPasswordResetTokenByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswordResetTokenByHash", reflect.TypeOf((*MockUserRepo)(nil).GetPasswordResetTokenByHash), ctx, tokenHash)
}

// GetVerificationTokenByHash mocks base method.
func (m *MockUserRepo) GetVerificationTokenByHash(ctx context.Context, tokenHash string) (entity.EmailVerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerificationTokenByHash", ctx, tokenHash)
	ret0, _ := ret[0].(entity.EmailVerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVerificationTokenByHash indicates an expected call of GetVerificationTokenByHash.
func (mr *MockUserRepoMockRecorder) GetVerificationTokenByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerificationTokenByHash", reflect.TypeOf((*MockUserRepo)(nil).GetVerificationTokenByHash), ctx, tokenHash)
}

// RecordAuthLoginFingerprint mocks base method.
func (m *MockUserRepo) RecordAuthLoginFingerprint(ctx context.Context, fingerprint entity.AuthLoginFingerprint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordAuthLoginFingerprint", ctx, fingerprint)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordAuthLoginFingerprint indicates an expected call of RecordAuthLoginFingerprint.
func (mr *MockUserRepoMockRecorder) RecordAuthLoginFingerprint(ctx, fingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordAuthLoginFingerprint", reflect.TypeOf((*MockUserRepo)(nil).RecordAuthLoginFingerprint), ctx, fingerprint)
}

// ReplaceEmailChangeToken mocks base method.
func (m *MockUserRepo) ReplaceEmailChangeToken(ctx context.Context, token *entity.EmailChangeToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceEmailChangeToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceEmailChangeToken indicates an expected call of ReplaceEmailChangeToken.
func (mr *MockUserRepoMockRecorder) ReplaceEmailChangeToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceEmailChangeToken", reflect.TypeOf((*MockUserRepo)(nil).ReplaceEmailChangeToken), ctx, token)
}

// ReplacePasswordResetToken mocks base method.
func (m *MockUserRepo) ReplacePasswordResetToken(ctx context.Context, token *entity.PasswordResetToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplacePasswordResetToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplacePasswordResetToken indicates an expected call of ReplacePasswordResetToken.
func (mr *MockUserRepoMockRecorder) ReplacePasswordResetToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplacePasswordResetToken", reflect.TypeOf((*MockUserRepo)(nil).ReplacePasswordResetToken), ctx, token)
}

// ReplaceVerificationToken mocks base method.
func (m *MockUserRepo) ReplaceVerificationToken(ctx context.Context, token *entity.EmailVerificationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceVerificationToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceVerificationToken indicates an expected call of ReplaceVerificationToken.
func (mr *MockUserRepoMockRecorder) ReplaceVerificationToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceVerificationToken", reflect.TypeOf((*MockUserRepo)(nil).ReplaceVerificationToken), ctx, token)
}

// ResetPasswordWithToken mocks base method.
func (m *MockUserRepo) ResetPasswordWithToken(ctx context.Context, tokenID, userID, passwordHash string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPasswordWithToken", ctx, tokenID, userID, passwordHash)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetPasswordWithToken indicates an expected call of ResetPasswordWithToken.
func (mr *MockUserRepoMockRecorder) ResetPasswordWithToken(ctx, tokenID, userID, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPasswordWithToken", reflect.TypeOf((*MockUserRepo)(nil).ResetPasswordWithToken), ctx, tokenID, userID, passwordHash)
}

// RevokeUnusedEmailChangeTokens mocks base method.
func (m *MockUserRepo) RevokeUnusedEmailChangeTokens(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeUnusedEmailChangeTokens", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeUnusedEmailChangeTokens indicates an expected call of RevokeUnusedEmailChangeTokens.
func (mr *MockUserRepoMockRecorder) RevokeUnusedEmailChangeTokens(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeUnusedEmailChangeTokens", reflect.TypeOf((*MockUserRepo)(nil).RevokeUnusedEmailChangeTokens), ctx, userID)
}

// RevokeUnusedPasswordResetTokens mocks base method.
func (m *MockUserRepo) RevokeUnusedPasswordResetTokens(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeUnusedPasswordResetTokens", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeUnusedPasswordResetTokens indicates an expected call of RevokeUnusedPasswordResetTokens.
func (mr *MockUserRepoMockRecorder) RevokeUnusedPasswordResetTokens(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeUnusedPasswordResetTokens", reflect.TypeOf((*MockUserRepo)(nil).RevokeUnusedPasswordResetTokens), ctx, userID)
}

// RevokeUnusedVerificationTokens mocks base method.
func (m *MockUserRepo) RevokeUnusedVerificationTokens(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeUnusedVerificationTokens", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeUnusedVerificationTokens indicates an expected call of RevokeUnusedVerificationTokens.
func (mr *MockUserRepoMockRecorder) RevokeUnusedVerificationTokens(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeUnusedVerificationTokens", reflect.TypeOf((*MockUserRepo)(nil).RevokeUnusedVerificationTokens), ctx, userID)
}

// SetRoleByEmail mocks base method.
func (m *MockUserRepo) SetRoleByEmail(ctx context.Context, email, role string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRoleByEmail", ctx, email, role)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetRoleByEmail indicates an expected call of SetRoleByEmail.
func (mr *MockUserRepoMockRecorder) SetRoleByEmail(ctx, email, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoleByEmail", reflect.TypeOf((*MockUserRepo)(nil).SetRoleByEmail), ctx, email, role)
}

// Store mocks base method.
func (m *MockUserRepo) Store(ctx context.Context, user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockUserRepoMockRecorder) Store(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockUserRepo)(nil).Store), ctx, user)
}

// StoreWithVerificationToken mocks base method.
func (m *MockUserRepo) StoreWithVerificationToken(ctx context.Context, user *entity.User, token *entity.EmailVerificationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreWithVerificationToken", ctx, user, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreWithVerificationToken indicates an expected call of StoreWithVerificationToken.
func (mr *MockUserRepoMockRecorder) StoreWithVerificationToken(ctx, user, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreWithVerificationToken", reflect.TypeOf((*MockUserRepo)(nil).StoreWithVerificationToken), ctx, user, token)
}

// UpsertPreferences mocks base method.
func (m *MockUserRepo) UpsertPreferences(ctx context.Context, preferences entity.UserPreferences) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPreferences", ctx, preferences)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertPreferences indicates an expected call of UpsertPreferences.
func (mr *MockUserRepoMockRecorder) UpsertPreferences(ctx, preferences any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPreferences", reflect.TypeOf((*MockUserRepo)(nil).UpsertPreferences), ctx, preferences)
}

// UpsertProfile mocks base method.
func (m *MockUserRepo) UpsertProfile(ctx context.Context, profile entity.UserProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertProfile", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertProfile indicates an expected call of UpsertProfile.
func (mr *MockUserRepoMockRecorder) UpsertProfile(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertProfile", reflect.TypeOf((*MockUserRepo)(nil).UpsertProfile), ctx, profile)
}

// VerifyEmailWithToken mocks base method.
func (m *MockUserRepo) VerifyEmailWithToken(ctx context.Context, tokenID, userID string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmailWithToken", ctx, tokenID, userID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyEmailWithToken indicates an expected call of VerifyEmailWithToken.
func (mr *MockUserRepoMockRecorder) VerifyEmailWithToken(ctx, tokenID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmailWithToken", reflect.TypeOf((*MockUserRepo)(nil).VerifyEmailWithToken), ctx, tokenID, userID)
}

// MockAuthRateLimitRepo is a mock of AuthRateLimitRepo interface.
type MockAuthRateLimitRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRateLimitRepoMockRecorder
	isgomock struct{}
}

// MockAuthRateLimitRepoMockRecorder is the mock recorder for MockAuthRateLimitRepo.
type MockAuthRateLimitRepoMockRecorder struct {
	mock *MockAuthRateLimitRepo
}

// NewMockAuthRateLimitRepo creates a new mock instance.
func NewMockAuthRateLimitRepo(ctrl *gomock.Controller) *MockAuthRateLimitRepo {
	mock := &MockAuthRateLimitRepo{ctrl: ctrl}
	mock.recorder = &MockAuthRateLimitRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRateLimitRepo) EXPECT() *MockAuthRateLimitRepoMockRecorder {
	return m.recorder
}

// IncrementAuthRateLimit mocks base method.
func (m *MockAuthRateLimitRepo) IncrementAuthRateLimit(ctx context.Context, limit entity.AuthRateLimit) (entity.AuthRateLimitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAuthRateLimit", ctx, limit)
	ret0, _ := ret[0].(entity.AuthRateLimitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementAuthRateLimit indicates an expected call of IncrementAuthRateLimit.
func (mr *MockAuthRateLimitRepoMockRecorder) IncrementAuthRateLimit(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAuthRateLimit", reflect.TypeOf((*MockAuthRateLimitRepo)(nil).IncrementAuthRateLimit), ctx, limit)
}

// MockAuthAuditRepo is a mock of AuthAuditRepo interface.
type MockAuthAuditRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAuthAuditRepoMockRecorder
	isgomock struct{}
}

// MockAuthAuditRepoMockRecorder is the mock recorder for MockAuthAuditRepo.
type MockAuthAuditRepoMockRecorder struct {
	mock *MockAuthAuditRepo
}

// NewMockAuthAuditRepo creates a new mock instance.
func NewMockAuthAuditRepo(ctrl *gomock.Controller) *MockAuthAuditRepo {
	mock := &MockAuthAuditRepo{ctrl: ctrl}
	mock.recorder = &MockAuthAuditRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthAuditRepo) EXPECT() *MockAuthAuditRepoMockRecorder {
	return m.recorder
}

// StoreAuthAuditLog mocks base method.
func (m *MockAuthAuditRepo) StoreAuthAuditLog(ctx context.Context, log entity.AuthAuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreAuthAuditLog", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreAuthAuditLog indicates an expected call of StoreAuthAuditLog.
func (mr *MockAuthAuditRepoMockRecorder) StoreAuthAuditLog(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreAuthAuditLog", reflect.TypeOf((*MockAuthAuditRepo)(nil).StoreAuthAuditLog), ctx, log)
}

// MockEmailSender is a mock of EmailSender interface.
type MockEmailSender struct {
	ctrl     *gomock.Controller
	recorder *MockEmailSenderMockRecorder
	isgomock struct{}
}

// MockEmailSenderMockRecorder is the mock recorder for MockEmailSender.
type MockEmailSenderMockRecorder struct {
	mock *MockEmailSender
}

// NewMockEmailSender creates a new mock instance.
func NewMockEmailSender(ctrl *gomock.Controller) *MockEmailSender {
	mock := &MockEmailSender{ctrl: ctrl}
	mock.recorder = &MockEmailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailSender) EXPECT() *MockEmailSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockEmailSender) Send(ctx context.Context, message entity.EmailMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockEmailSenderMockRecorder) Send(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockEmailSender)(nil).Send), ctx, message)
}

// MockTaskRepo is a mock of TaskRepo interface.
type MockTaskRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepoMockRecorder
	isgomock struct{}
}

// MockTaskRepoMockRecorder is the mock recorder for MockTaskRepo.
type MockTaskRepoMockRecorder struct {
	mock *MockTaskRepo
}

// NewMockTaskRepo creates a new mock instance.
func NewMockTaskRepo(ctrl *gomock.Controller) *MockTaskRepo {
	mock := &MockTaskRepo{ctrl: ctrl}
	mock.recorder = &MockTaskRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepo) EXPECT() *MockTaskRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTaskRepo) Delete(ctx context.Context, userID, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskRepoMockRecorder) Delete(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaskRepo)(nil).Delete), ctx, userID, taskID)
}

// GetByID mocks base method.
func (m *MockTaskRepo) GetByID(ctx context.Context, userID, taskID string) (entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID, taskID)
	ret0, _ := ret[0].(entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTaskRepoMockRecorder) GetByID(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTaskRepo)(nil).GetByID), ctx, userID, taskID)
}

// List mocks base method.
func (m *MockTaskRepo) List(ctx context.Context, userID string, filter repo.TaskFilter) ([]entity.Task, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, filter)
	ret0, _ := ret[0].([]entity.Task)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTaskRepoMockRecorder) List(ctx, userID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskRepo)(nil).List), ctx, userID, filter)
}

// Store mocks base method.
func (m *MockTaskRepo) Store(ctx context.Context, task *entity.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTaskRepoMockRecorder) Store(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTaskRepo)(nil).Store), ctx, task)
}

// Update mocks base method.
func (m *MockTaskRepo) Update(ctx context.Context, task *entity.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTaskRepoMockRecorder) Update(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskRepo)(nil).Update), ctx, task)
}

// MockReaderRepo is a mock of ReaderRepo interface.
type MockReaderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockReaderRepoMockRecorder
	isgomock struct{}
}

// MockReaderRepoMockRecorder is the mock recorder for MockReaderRepo.
type MockReaderRepoMockRecorder struct {
	mock *MockReaderRepo
}

// NewMockReaderRepo creates a new mock instance.
func NewMockReaderRepo(ctrl *gomock.Controller) *MockReaderRepo {
	mock := &MockReaderRepo{ctrl: ctrl}
	mock.recorder = &MockReaderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReaderRepo) EXPECT() *MockReaderRepoMockRecorder {
	return m.recorder
}

// CreateTranslationFeedback mocks base method.
func (m *MockReaderRepo) CreateTranslationFeedback(ctx context.Context, feedback entity.TranslationFeedback) (entity.TranslationFeedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTranslationFeedback", ctx, feedback)
	ret0, _ := ret[0].(entity.TranslationFeedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTranslationFeedback indicates an expected call of CreateTranslationFeedback.
func (mr *MockReaderRepoMockRecorder) CreateTranslationFeedback(ctx, feedback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTranslationFeedback", reflect.TypeOf((*MockReaderRepo)(nil).CreateTranslationFeedback), ctx, feedback)
}

// GetBook mocks base method.
func (m *MockReaderRepo) GetBook(ctx context.Context, bookID int, lang string) (entity.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBook", ctx, bookID, lang)
	ret0, _ := ret[0].(entity.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBook indicates an expected call of GetBook.
func (mr *MockReaderRepoMockRecorder) GetBook(ctx, bookID, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBook", reflect.TypeOf((*MockReaderRepo)(nil).GetBook), ctx, bookID, lang)
}

// GetBookPage mocks base method.
func (m *MockReaderRepo) GetBookPage(ctx context.Context, bookID, pageID int) (entity.BookPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookPage", ctx, bookID, pageID)
	ret0, _ := ret[0].(entity.BookPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookPage indicates an expected call of GetBookPage.
func (mr *MockReaderRepoMockRecorder) GetBookPage(ctx, bookID, pageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookPage", reflect.TypeOf((*MockReaderRepo)(nil).GetBookPage), ctx, bookID, pageID)
}

// GetSection mocks base method.
func (m *MockReaderRepo) GetSection(ctx context.Context, bookID, headingID int, lang string) (entity.BookSection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSection", ctx, bookID, headingID, lang)
	ret0, _ := ret[0].(entity.BookSection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSection indicates an expected call of GetSection.
func (mr *MockReaderRepoMockRecorder) GetSection(ctx, bookID, headingID, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSection", reflect.TypeOf((*MockReaderRepo)(nil).GetSection), ctx, bookID, headingID, lang)
}

// ListAuthors mocks base method.
func (m *MockReaderRepo) ListAuthors(ctx context.Context, filter repo.AuthorFilter) ([]entity.Author, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuthors", ctx, filter)
	ret0, _ := ret[0].([]entity.Author)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAuthors indicates an expected call of ListAuthors.
func (mr *MockReaderRepoMockRecorder) ListAuthors(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuthors", reflect.TypeOf((*MockReaderRepo)(nil).ListAuthors), ctx, filter)
}

// ListBookHeadings mocks base method.
func (m *MockReaderRepo) ListBookHeadings(ctx context.Context, bookID int, query string) ([]entity.BookHeading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookHeadings", ctx, bookID, query)
	ret0, _ := ret[0].([]entity.BookHeading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBookHeadings indicates an expected call of ListBookHeadings.
func (mr *MockReaderRepoMockRecorder) ListBookHeadings(ctx, bookID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookHeadings", reflect.TypeOf((*MockReaderRepo)(nil).ListBookHeadings), ctx, bookID, query)
}

// ListBookPages mocks base method.
func (m *MockReaderRepo) ListBookPages(ctx context.Context, bookID int, filter repo.PageFilter) ([]entity.BookPage, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookPages", ctx, bookID, filter)
	ret0, _ := ret[0].([]entity.BookPage)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBookPages indicates an expected call of ListBookPages.
func (mr *MockReaderRepoMockRecorder) ListBookPages(ctx, bookID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookPages", reflect.TypeOf((*MockReaderRepo)(nil).ListBookPages), ctx, bookID, filter)
}

// ListBooks mocks base method.
func (m *MockReaderRepo) ListBooks(ctx context.Context, filter repo.BookFilter) ([]entity.Book, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBooks", ctx, filter)
	ret0, _ := ret[0].([]entity.Book)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBooks indicates an expected call of ListBooks.
func (mr *MockReaderRepoMockRecorder) ListBooks(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBooks", reflect.TypeOf((*MockReaderRepo)(nil).ListBooks), ctx, filter)
}

// ListCategories mocks base method.
func (m *MockReaderRepo) ListCategories(ctx context.Context, lang string) ([]entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", ctx, lang)
	ret0, _ := ret[0].([]entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockReaderRepoMockRecorder) ListCategories(ctx, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockReaderRepo)(nil).ListCategories), ctx, lang)
}

// ListTOCEntries mocks base method.
func (m *MockReaderRepo) ListTOCEntries(ctx context.Context, bookID int, lang string, includeAudio bool) ([]entity.BookTOCEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTOCEntries", ctx, bookID, lang, includeAudio)
	ret0, _ := ret[0].([]entity.BookTOCEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTOCEntries indicates an expected call of ListTOCEntries.
func (mr *MockReaderRepoMockRecorder) ListTOCEntries(ctx, bookID, lang, includeAudio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTOCEntries", reflect.TypeOf((*MockReaderRepo)(nil).ListTOCEntries), ctx, bookID, lang, includeAudio)
}

// MockBookRAGRepo is a mock of BookRAGRepo interface.
type MockBookRAGRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBookRAGRepoMockRecorder
	isgomock struct{}
}

// MockBookRAGRepoMockRecorder is the mock recorder for MockBookRAGRepo.
type MockBookRAGRepoMockRecorder struct {
	mock *MockBookRAGRepo
}

// NewMockBookRAGRepo creates a new mock instance.
func NewMockBookRAGRepo(ctrl *gomock.Controller) *MockBookRAGRepo {
	mock := &MockBookRAGRepo{ctrl: ctrl}
	mock.recorder = &MockBookRAGRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookRAGRepo) EXPECT() *MockBookRAGRepoMockRecorder {
	return m.recorder
}

// GetRAGBookDocument mocks base method.
func (m *MockBookRAGRepo) GetRAGBookDocument(ctx context.Context, bookID int, lang string) (entity.RAGBookDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRAGBookDocument", ctx, bookID, lang)
	ret0, _ := ret[0].(entity.RAGBookDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRAGBookDocument indicates an expected call of GetRAGBookDocument.
func (mr *MockBookRAGRepoMockRecorder) GetRAGBookDocument(ctx, bookID, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRAGBookDocument", reflect.TypeOf((*MockBookRAGRepo)(nil).GetRAGBookDocument), ctx, bookID, lang)
}

// GetRAGPageSources mocks base method.
func (m *MockBookRAGRepo) GetRAGPageSources(ctx context.Context, bookID int, headingIDs, focusPageIDs []int, lang string, maxPages int) ([]entity.RAGPageSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRAGPageSources", ctx, bookID, headingIDs, focusPageIDs, lang, maxPages)
	ret0, _ := ret[0].([]entity.RAGPageSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRAGPageSources indicates an expected call of GetRAGPageSources.
func (mr *MockBookRAGRepoMockRecorder) GetRAGPageSources(ctx, bookID, headingIDs, focusPageIDs, lang, maxPages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRAGPageSources", reflect.TypeOf((*MockBookRAGRepo)(nil).GetRAGPageSources), ctx, bookID, headingIDs, focusPageIDs, lang, maxPages)
}

// ListRAGStructure mocks base method.
func (m *MockBookRAGRepo) ListRAGStructure(ctx context.Context, bookID int, lang string) ([]entity.RAGStructureNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRAGStructure", ctx, bookID, lang)
	ret0, _ := ret[0].([]entity.RAGStructureNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRAGStructure indicates an expected call of ListRAGStructure.
func (mr *MockBookRAGRepoMockRecorder) ListRAGStructure(ctx, bookID, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRAGStructure", reflect.TypeOf((*MockBookRAGRepo)(nil).ListRAGStructure), ctx, bookID, lang)
}

// SearchRAGPages mocks base method.
func (m *MockBookRAGRepo) SearchRAGPages(ctx context.Context, bookID int, query, lang string, limit int) ([]entity.RAGSearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRAGPages", ctx, bookID, query, lang, limit)
	ret0, _ := ret[0].([]entity.RAGSearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRAGPages indicates an expected call of SearchRAGPages.
func (mr *MockBookRAGRepoMockRecorder) SearchRAGPages(ctx, bookID, query, lang, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRAGPages", reflect.TypeOf((*MockBookRAGRepo)(nil).SearchRAGPages), ctx, bookID, query, lang, limit)
}

// MockQuranRepo is a mock of QuranRepo interface.
type MockQuranRepo struct {
	ctrl     *gomock.Controller
	recorder *MockQuranRepoMockRecorder
	isgomock struct{}
}

// MockQuranRepoMockRecorder is the mock recorder for MockQuranRepo.
type MockQuranRepoMockRecorder struct {
	mock *MockQuranRepo
}

// NewMockQuranRepo creates a new mock instance.
func NewMockQuranRepo(ctrl *gomock.Controller) *MockQuranRepo {
	mock := &MockQuranRepo{ctrl: ctrl}
	mock.recorder = &MockQuranRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuranRepo) EXPECT() *MockQuranRepoMockRecorder {
	return m.recorder
}

// GetAyah mocks base method.
func (m *MockQuranRepo) GetAyah(ctx context.Context, ayahKey, lang, translationSource string, includeAudio bool, recitationID string) (entity.QuranAyah, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAyah", ctx, ayahKey, lang, translationSource, includeAudio, recitationID)
	ret0, _ := ret[0].(entity.QuranAyah)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAyah indicates an expected call of GetAyah.
func (mr *MockQuranRepoMockRecorder) GetAyah(ctx, ayahKey, lang, translationSource, includeAudio, recitationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAyah", reflect.TypeOf((*MockQuranRepo)(nil).GetAyah), ctx, ayahKey, lang, translationSource, includeAudio, recitationID)
}

// GetSurah mocks base method.
func (m *MockQuranRepo) GetSurah(ctx context.Context, surahID int, lang string) (entity.QuranSurah, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSurah", ctx, surahID, lang)
	ret0, _ := ret[0].(entity.QuranSurah)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSurah indicates an expected call of GetSurah.
func (mr *MockQuranRepoMockRecorder) GetSurah(ctx, surahID, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSurah", reflect.TypeOf((*MockQuranRepo)(nil).GetSurah), ctx, surahID, lang)
}

// ListBookQuranReferences mocks base method.
func (m *MockQuranRepo) ListBookQuranReferences(ctx context.Context, filter repo.QuranBookReferenceFilter) ([]entity.BookQuranReference, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookQuranReferences", ctx, filter)
	ret0, _ := ret[0].([]entity.BookQuranReference)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBookQuranReferences indicates an expected call of ListBookQuranReferences.
func (mr *MockQuranRepoMockRecorder) ListBookQuranReferences(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookQuranReferences", reflect.TypeOf((*MockQuranRepo)(nil).ListBookQuranReferences), ctx, filter)
}

// ListMissingQuranAssets mocks base method.
func (m *MockQuranRepo) ListMissingQuranAssets(ctx context.Context, filter repo.MissingQuranAssetFilter) (entity.AdminMissingQuranAssets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMissingQuranAssets", ctx, filter)
	ret0, _ := ret[0].(entity.AdminMissingQuranAssets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMissingQuranAssets indicates an expected call of ListMissingQuranAssets.
func (mr *MockQuranRepoMockRecorder) ListMissingQuranAssets(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMissingQuranAssets", reflect.TypeOf((*MockQuranRepo)(nil).ListMissingQuranAssets), ctx, filter)
}

// ListNavigationAyahs mocks base method.
func (m *MockQuranRepo) ListNavigationAyahs(ctx context.Context, kind string, number int, lang, translationSource string, includeTranslation, includeAudio bool, recitationID string) ([]entity.QuranAyah, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNavigationAyahs", ctx, kind, number, lang, translationSource, includeTranslation, includeAudio, recitationID)
	ret0, _ := ret[0].([]entity.QuranAyah)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNavigationAyahs indicates an expected call of ListNavigationAyahs.
func (mr *MockQuranRepoMockRecorder) ListNavigationAyahs(ctx, kind, number, lang, translationSource, includeTranslation, includeAudio, recitationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNavigationAyahs", reflect.TypeOf((*MockQuranRepo)(nil).ListNavigationAyahs), ctx, kind, number, lang, translationSource, includeTranslation, includeAudio, recitationID)
}

// ListNavigationSegments mocks base method.
func (m *MockQuranRepo) ListNavigationSegments(ctx context.Context, kind, lang string) ([]entity.QuranNavigationSegment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNavigationSegments", ctx, kind, lang)
	ret0, _ := ret[0].([]entity.QuranNavigationSegment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNavigationSegments indicates an expected call of ListNavigationSegments.
func (mr *MockQuranRepoMockRecorder) ListNavigationSegments(ctx, kind, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNavigationSegments", reflect.TypeOf((*MockQuranRepo)(nil).ListNavigationSegments), ctx, kind, lang)
}

// ListRecitations mocks base method.
func (m *MockQuranRepo) ListRecitations(ctx context.Context) ([]entity.QuranRecitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecitations", ctx)
	ret0, _ := ret[0].([]entity.QuranRecitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecitations indicates an expected call of ListRecitations.
func (mr *MockQuranRepoMockRecorder) ListRecitations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecitations", reflect.TypeOf((*MockQuranRepo)(nil).ListRecitations), ctx)
}

// ListSurahAyahs mocks base method.
func (m *MockQuranRepo) ListSurahAyahs(ctx context.Context, surahID, fromAyah, toAyah int, lang, translationSource string, includeTranslation, includeAudio bool, recitationID string) ([]entity.QuranAyah, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSurahAyahs", ctx, surahID, fromAyah, toAyah, lang, translationSource, includeTranslation, includeAudio, recitationID)
	ret0, _ := ret[0].([]entity.QuranAyah)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSurahAyahs indicates an expected call of ListSurahAyahs.
func (mr *MockQuranRepoMockRecorder) ListSurahAyahs(ctx, surahID, fromAyah, toAyah, lang, translationSource, includeTranslation, includeAudio, recitationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSurahAyahs", reflect.TypeOf((*MockQuranRepo)(nil).ListSurahAyahs), ctx, surahID, fromAyah, toAyah, lang, translationSource, includeTranslation, includeAudio, recitationID)
}

// ListSurahs mocks base method.
func (m *MockQuranRepo) ListSurahs(ctx context.Context, lang string, includeInfo bool) ([]entity.QuranSurah, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSurahs", ctx, lang, includeInfo)
	ret0, _ := ret[0].([]entity.QuranSurah)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSurahs indicates an expected call of ListSurahs.
func (mr *MockQuranRepoMockRecorder) ListSurahs(ctx, lang, includeInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSurahs", reflect.TypeOf((*MockQuranRepo)(nil).ListSurahs), ctx, lang, includeInfo)
}

// ListTranslationSources mocks base method.
func (m *MockQuranRepo) ListTranslationSources(ctx context.Context, lang string) ([]entity.QuranTranslationSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTranslationSources", ctx, lang)
	ret0, _ := ret[0].([]entity.QuranTranslationSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTranslationSources indicates an expected call of ListTranslationSources.
func (mr *MockQuranRepoMockRecorder) ListTranslationSources(ctx, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTranslationSources", reflect.TypeOf((*MockQuranRepo)(nil).ListTranslationSources), ctx, lang)
}

// SearchAyahs mocks base method.
func (m *MockQuranRepo) SearchAyahs(ctx context.Context, filter repo.QuranSearchFilter) ([]entity.QuranSearchResult, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAyahs", ctx, filter)
	ret0, _ := ret[0].([]entity.QuranSearchResult)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchAyahs indicates an expected call of SearchAyahs.
func (mr *MockQuranRepoMockRecorder) SearchAyahs(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAyahs", reflect.TypeOf((*MockQuranRepo)(nil).SearchAyahs), ctx, filter)
}

// MockPersonalRepo is a mock of PersonalRepo interface.
type MockPersonalRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPersonalRepoMockRecorder
	isgomock struct{}
}

// MockPersonalRepoMockRecorder is the mock recorder for MockPersonalRepo.
type MockPersonalRepoMockRecorder struct {
	mock *MockPersonalRepo
}

// NewMockPersonalRepo creates a new mock instance.
func NewMockPersonalRepo(ctrl *gomock.Controller) *MockPersonalRepo {
	mock := &MockPersonalRepo{ctrl: ctrl}
	mock.recorder = &MockPersonalRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonalRepo) EXPECT() *MockPersonalRepoMockRecorder {
	return m.recorder
}

// DeleteSavedItem mocks base method.
func (m *MockPersonalRepo) DeleteSavedItem(ctx context.Context, userID, savedItemID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSavedItem", ctx, userID, savedItemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSavedItem indicates an expected call of DeleteSavedItem.
func (mr *MockPersonalRepoMockRecorder) DeleteSavedItem(ctx, userID, savedItemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSavedItem", reflect.TypeOf((*MockPersonalRepo)(nil).DeleteSavedItem), ctx, userID, savedItemID)
}

// GetProgress mocks base method.
func (m *MockPersonalRepo) GetProgress(ctx context.Context, userID string, bookID int) (entity.ReadingProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProgress", ctx, userID, bookID)
	ret0, _ := ret[0].(entity.ReadingProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProgress indicates an expected call of GetProgress.
func (mr *MockPersonalRepoMockRecorder) GetProgress(ctx, userID, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProgress", reflect.TypeOf((*MockPersonalRepo)(nil).GetProgress), ctx, userID, bookID)
}

// GetQuranProgress mocks base method.
func (m *MockPersonalRepo) GetQuranProgress(ctx context.Context, userID string) (entity.QuranReadingProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuranProgress", ctx, userID)
	ret0, _ := ret[0].(entity.QuranReadingProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuranProgress indicates an expected call of GetQuranProgress.
func (mr *MockPersonalRepoMockRecorder) GetQuranProgress(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuranProgress", reflect.TypeOf((*MockPersonalRepo)(nil).GetQuranProgress), ctx, userID)
}

// GetQuranSurahProgress mocks base method.
func (m *MockPersonalRepo) GetQuranSurahProgress(ctx context.Context, userID string, surahID int) (entity.QuranReadingProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuranSurahProgress", ctx, userID, surahID)
	ret0, _ := ret[0].(entity.QuranReadingProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuranSurahProgress indicates an expected call of GetQuranSurahProgress.
func (mr *MockPersonalRepoMockRecorder) GetQuranSurahProgress(ctx, userID, surahID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuranSurahProgress", reflect.TypeOf((*MockPersonalRepo)(nil).GetQuranSurahProgress), ctx, userID, surahID)
}

// ListQuranSurahProgress mocks base method.
func (m *MockPersonalRepo) ListQuranSurahProgress(ctx context.Context, userID string) ([]entity.QuranReadingProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListQuranSurahProgress", ctx, userID)
	ret0, _ := ret[0].([]entity.QuranReadingProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListQuranSurahProgress indicates an expected call of ListQuranSurahProgress.
func (mr *MockPersonalRepoMockRecorder) ListQuranSurahProgress(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListQuranSurahProgress", reflect.TypeOf((*MockPersonalRepo)(nil).ListQuranSurahProgress), ctx, userID)
}

// ListSavedItemTags mocks base method.
func (m *MockPersonalRepo) ListSavedItemTags(ctx context.Context, userID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSavedItemTags", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSavedItemTags indicates an expected call of ListSavedItemTags.
func (mr *MockPersonalRepoMockRecorder) ListSavedItemTags(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSavedItemTags", reflect.TypeOf((*MockPersonalRepo)(nil).ListSavedItemTags), ctx, userID)
}

// ListSavedItems mocks base method.
func (m *MockPersonalRepo) ListSavedItems(ctx context.Context, userID string, filter repo.SavedItemFilter) ([]entity.SavedItem, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSavedItems", ctx, userID, filter)
	ret0, _ := ret[0].([]entity.SavedItem)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSavedItems indicates an expected call of ListSavedItems.
func (mr *MockPersonalRepoMockRecorder) ListSavedItems(ctx, userID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSavedItems", reflect.TypeOf((*MockPersonalRepo)(nil).ListSavedItems), ctx, userID, filter)
}

// SaveProgress mocks base method.
func (m *MockPersonalRepo) SaveProgress(ctx context.Context, progress entity.ReadingProgress) (entity.ReadingProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveProgress", ctx, progress)
	ret0, _ := ret[0].(entity.ReadingProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveProgress indicates an expected call of SaveProgress.
func (mr *MockPersonalRepoMockRecorder) SaveProgress(ctx, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveProgress", reflect.TypeOf((*MockPersonalRepo)(nil).SaveProgress), ctx, progress)
}

// SaveQuranProgress mocks base method.
func (m *MockPersonalRepo) SaveQuranProgress(ctx context.Context, progress entity.QuranReadingProgress) (entity.QuranReadingProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveQuranProgress", ctx, progress)
	ret0, _ := ret[0].(entity.QuranReadingProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveQuranProgress indicates an expected call of SaveQuranProgress.
func (mr *MockPersonalRepoMockRecorder) SaveQuranProgress(ctx, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveQuranProgress", reflect.TypeOf((*MockPersonalRepo)(nil).SaveQuranProgress), ctx, progress)
}

// UpdateSavedItem mocks base method.
func (m *MockPersonalRepo) UpdateSavedItem(ctx context.Context, item entity.SavedItem) (entity.SavedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSavedItem", ctx, item)
	ret0, _ := ret[0].(entity.SavedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSavedItem indicates an expected call of UpdateSavedItem.
func (mr *MockPersonalRepoMockRecorder) UpdateSavedItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSavedItem", reflect.TypeOf((*MockPersonalRepo)(nil).UpdateSavedItem), ctx, item)
}

// UpsertSavedItem mocks base method.
func (m *MockPersonalRepo) UpsertSavedItem(ctx context.Context, item entity.SavedItem) (entity.SavedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSavedItem", ctx, item)
	ret0, _ := ret[0].(entity.SavedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertSavedItem indicates an expected call of UpsertSavedItem.
func (mr *MockPersonalRepoMockRecorder) UpsertSavedItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSavedItem", reflect.TypeOf((*MockPersonalRepo)(nil).UpsertSavedItem), ctx, item)
}

// MockEditorialRepo is a mock of EditorialRepo interface.
type MockEditorialRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEditorialRepoMockRecorder
	isgomock struct{}
}

// MockEditorialRepoMockRecorder is the mock recorder for MockEditorialRepo.
type MockEditorialRepoMockRecorder struct {
	mock *MockEditorialRepo
}

// NewMockEditorialRepo creates a new mock instance.
func NewMockEditorialRepo(ctrl *gomock.Controller) *MockEditorialRepo {
	mock := &MockEditorialRepo{ctrl: ctrl}
	mock.recorder = &MockEditorialRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEditorialRepo) EXPECT() *MockEditorialRepoMockRecorder {
	return m.recorder
}

// AddCollectionItem mocks base method.
func (m *MockEditorialRepo) AddCollectionItem(ctx context.Context, actorID, slug string, bookID int, sortOrder *int) (entity.BookCollectionItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCollectionItem", ctx, actorID, slug, bookID, sortOrder)
	ret0, _ := ret[0].(entity.BookCollectionItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCollectionItem indicates an expected call of AddCollectionItem.
func (mr *MockEditorialRepoMockRecorder) AddCollectionItem(ctx, actorID, slug, bookID, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCollectionItem", reflect.TypeOf((*MockEditorialRepo)(nil).AddCollectionItem), ctx, actorID, slug, bookID, sortOrder)
}

// GetPageEdit mocks base method.
func (m *MockEditorialRepo) GetPageEdit(ctx context.Context, bookID, pageID int) (entity.AdminPageEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPageEdit", ctx, bookID, pageID)
	ret0, _ := ret[0].(entity.AdminPageEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPageEdit indicates an expected call of GetPageEdit.
func (mr *MockEditorialRepoMockRecorder) GetPageEdit(ctx, bookID, pageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPageEdit", reflect.TypeOf((*MockEditorialRepo)(nil).GetPageEdit), ctx, bookID, pageID)
}

// ListBooks mocks base method.
func (m *MockEditorialRepo) ListBooks(ctx context.Context, filter repo.EditorialBookFilter) ([]entity.Book, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBooks", ctx, filter)
	ret0, _ := ret[0].([]entity.Book)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBooks indicates an expected call of ListBooks.
func (mr *MockEditorialRepoMockRecorder) ListBooks(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBooks", reflect.TypeOf((*MockEditorialRepo)(nil).ListBooks), ctx, filter)
}

// ListMissingReaderAssets mocks base method.
func (m *MockEditorialRepo) ListMissingReaderAssets(ctx context.Context, filter repo.MissingReaderAssetFilter) (entity.AdminMissingReaderAssets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMissingReaderAssets", ctx, filter)
	ret0, _ := ret[0].(entity.AdminMissingReaderAssets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMissingReaderAssets indicates an expected call of ListMissingReaderAssets.
func (mr *MockEditorialRepoMockRecorder) ListMissingReaderAssets(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMissingReaderAssets", reflect.TypeOf((*MockEditorialRepo)(nil).ListMissingReaderAssets), ctx, filter)
}

// ListTranslationFeedbacks mocks base method.
func (m *MockEditorialRepo) ListTranslationFeedbacks(ctx context.Context, filter repo.TranslationFeedbackFilter) ([]entity.AdminTranslationFeedback, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTranslationFeedbacks", ctx, filter)
	ret0, _ := ret[0].([]entity.AdminTranslationFeedback)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTranslationFeedbacks indicates an expected call of ListTranslationFeedbacks.
func (mr *MockEditorialRepoMockRecorder) ListTranslationFeedbacks(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTranslationFeedbacks", reflect.TypeOf((*MockEditorialRepo)(nil).ListTranslationFeedbacks), ctx, filter)
}

// PublishHeadingDraft mocks base method.
func (m *MockEditorialRepo) PublishHeadingDraft(ctx context.Context, actorID string, bookID, headingID int) (entity.BookHeadingEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishHeadingDraft", ctx, actorID, bookID, headingID)
	ret0, _ := ret[0].(entity.BookHeadingEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishHeadingDraft indicates an expected call of PublishHeadingDraft.
func (mr *MockEditorialRepoMockRecorder) PublishHeadingDraft(ctx, actorID, bookID, headingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishHeadingDraft", reflect.TypeOf((*MockEditorialRepo)(nil).PublishHeadingDraft), ctx, actorID, bookID, headingID)
}

// PublishMetadataDraft mocks base method.
func (m *MockEditorialRepo) PublishMetadataDraft(ctx context.Context, actorID string, bookID int) (entity.BookMetadataEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishMetadataDraft", ctx, actorID, bookID)
	ret0, _ := ret[0].(entity.BookMetadataEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishMetadataDraft indicates an expected call of PublishMetadataDraft.
func (mr *MockEditorialRepoMockRecorder) PublishMetadataDraft(ctx, actorID, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMetadataDraft", reflect.TypeOf((*MockEditorialRepo)(nil).PublishMetadataDraft), ctx, actorID, bookID)
}

// PublishPageDraft mocks base method.
func (m *MockEditorialRepo) PublishPageDraft(ctx context.Context, actorID string, bookID, pageID int) (entity.BookPageEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPageDraft", ctx, actorID, bookID, pageID)
	ret0, _ := ret[0].(entity.BookPageEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishPageDraft indicates an expected call of PublishPageDraft.
func (mr *MockEditorialRepoMockRecorder) PublishPageDraft(ctx, actorID, bookID, pageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPageDraft", reflect.TypeOf((*MockEditorialRepo)(nil).PublishPageDraft), ctx, actorID, bookID, pageID)
}

// ReopenTranslationFeedback mocks base method.
func (m *MockEditorialRepo) ReopenTranslationFeedback(ctx context.Context, actorID, feedbackID string) (entity.AdminTranslationFeedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReopenTranslationFeedback", ctx, actorID, feedbackID)
	ret0, _ := ret[0].(entity.AdminTranslationFeedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReopenTranslationFeedback indicates an expected call of ReopenTranslationFeedback.
func (mr *MockEditorialRepoMockRecorder) ReopenTranslationFeedback(ctx, actorID, feedbackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReopenTranslationFeedback", reflect.TypeOf((*MockEditorialRepo)(nil).ReopenTranslationFeedback), ctx, actorID, feedbackID)
}

// ResolveTranslationFeedback mocks base method.
func (m *MockEditorialRepo) ResolveTranslationFeedback(ctx context.Context, actorID, feedbackID string, note *string) (entity.AdminTranslationFeedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveTranslationFeedback", ctx, actorID, feedbackID, note)
	ret0, _ := ret[0].(entity.AdminTranslationFeedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveTranslationFeedback indicates an expected call of ResolveTranslationFeedback.
func (mr *MockEditorialRepoMockRecorder) ResolveTranslationFeedback(ctx, actorID, feedbackID, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveTranslationFeedback", reflect.TypeOf((*MockEditorialRepo)(nil).ResolveTranslationFeedback), ctx, actorID, feedbackID, note)
}

// SaveHeadingDraft mocks base method.
func (m *MockEditorialRepo) SaveHeadingDraft(ctx context.Context, actorID string, edit entity.BookHeadingEdit) (entity.BookHeadingEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveHeadingDraft", ctx, actorID, edit)
	ret0, _ := ret[0].(entity.BookHeadingEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveHeadingDraft indicates an expected call of SaveHeadingDraft.
func (mr *MockEditorialRepoMockRecorder) SaveHeadingDraft(ctx, actorID, edit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveHeadingDraft", reflect.TypeOf((*MockEditorialRepo)(nil).SaveHeadingDraft), ctx, actorID, edit)
}

// SaveMetadataDraft mocks base method.
func (m *MockEditorialRepo) SaveMetadataDraft(ctx context.Context, actorID string, edit entity.BookMetadataEdit) (entity.BookMetadataEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMetadataDraft", ctx, actorID, edit)
	ret0, _ := ret[0].(entity.BookMetadataEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMetadataDraft indicates an expected call of SaveMetadataDraft.
func (mr *MockEditorialRepoMockRecorder) SaveMetadataDraft(ctx, actorID, edit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMetadataDraft", reflect.TypeOf((*MockEditorialRepo)(nil).SaveMetadataDraft), ctx, actorID, edit)
}

// SavePageDraft mocks base method.
func (m *MockEditorialRepo) SavePageDraft(ctx context.Context, actorID string, edit entity.BookPageEdit) (entity.BookPageEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePageDraft", ctx, actorID, edit)
	ret0, _ := ret[0].(entity.BookPageEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SavePageDraft indicates an expected call of SavePageDraft.
func (mr *MockEditorialRepoMockRecorder) SavePageDraft(ctx, actorID, edit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePageDraft", reflect.TypeOf((*MockEditorialRepo)(nil).SavePageDraft), ctx, actorID, edit)
}

// TranslationFeedbackSummary mocks base method.
func (m *MockEditorialRepo) TranslationFeedbackSummary(ctx context.Context, filter repo.TranslationFeedbackFilter) (entity.AdminTranslationFeedbackSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranslationFeedbackSummary", ctx, filter)
	ret0, _ := ret[0].(entity.AdminTranslationFeedbackSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TranslationFeedbackSummary indicates an expected call of TranslationFeedbackSummary.
func (mr *MockEditorialRepoMockRecorder) TranslationFeedbackSummary(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranslationFeedbackSummary", reflect.TypeOf((*MockEditorialRepo)(nil).TranslationFeedbackSummary), ctx, filter)
}

// UpdatePublication mocks base method.
func (m *MockEditorialRepo) UpdatePublication(ctx context.Context, actorID string, publication entity.BookPublication) (entity.BookPublication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePublication", ctx, actorID, publication)
	ret0, _ := ret[0].(entity.BookPublication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePublication indicates an expected call of UpdatePublication.
func (mr *MockEditorialRepoMockRecorder) UpdatePublication(ctx, actorID, publication any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePublication", reflect.TypeOf((*MockEditorialRepo)(nil).UpdatePublication), ctx, actorID, publication)
}
